#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 1:50:04am
;;; DO NOT EDIT

(require (only-in "complex.rkt" c128vector-length c128vector-ref))

(provide c128vector->list)

(define (c128vector->list vec (start 0) (end (c128vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (c128vector-ref vec i) list)))))

