#lang racket/base
;;; Autogenerated on 2022-10-18T19:21:36
;;; DO NOT EDIT

(require (only-in "complex.rkt" c128vector-length c128vector-ref))

(require (only-in racket/unsafe/ops unsafe-bytes-length unsafe-flvector-length))

(provide c128vector->list)

(define (c128vector->list vec (start 0) (end (c128vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (c128vector-ref vec i) list)))))

