#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in "complex.rkt" c64vector-length c64vector-ref))

(provide c64vector->list)

(define (c64vector->list vec (start 0) (end (c64vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (c64vector-ref vec i) list)))))

