#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in ffi/vector f32vector-length f32vector-ref))

(provide f32vector->list)

(define (f32vector->list vec (start 0) (end (f32vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (f32vector-ref vec i) list)))))

