#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 5:02:47pm
;;; DO NOT EDIT

(require (only-in ffi/vector f64vector-length f64vector-ref))

(provide f64vector->list)

(define (f64vector->list vec (start 0) (end (f64vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (f64vector-ref vec i) list)))))

