#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in "flvector.rkt" flvector-length flvector-ref))

(provide flvector->list)

(define (flvector->list vec (start 0) (end (flvector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (flvector-ref vec i) list)))))

