#lang racket/base
;;; Autogenerated on 2022-10-18T20:24:08
;;; DO NOT EDIT

(require (only-in "flvector.rkt" flvector-length flvector-ref))

(require (only-in
          racket/unsafe/ops
          unsafe-bytes-length
          unsafe-flvector-length
          unsafe-fxvector-length))

(provide flvector->list)

(define (flvector->list vec (start 0) (end (unsafe-flvector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (flvector-ref vec i) list)))))

