#lang racket/base
;;; Autogenerated on 2024-10-18T15:19:08
;;; DO NOT EDIT

(require (only-in "fxvector.rkt" fxvector-length fxvector-ref))

(require (only-in
          racket/unsafe/ops
          unsafe-bytes-length
          unsafe-flvector-length
          unsafe-fxvector-length))

(provide fxvector->list)

(define (fxvector->list vec (start 0) (end (unsafe-fxvector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (fxvector-ref vec i) list)))))

