#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in ffi/vector s16vector-length s16vector-ref))

(provide s16vector->list)

(define (s16vector->list vec (start 0) (end (s16vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s16vector-ref vec i) list)))))

