#lang racket/base
;;; Autogenerated on 2022-10-18T20:24:08
;;; DO NOT EDIT

(require (only-in ffi/vector s16vector-length s16vector-ref))

(require (only-in
          racket/unsafe/ops
          unsafe-bytes-length
          unsafe-flvector-length
          unsafe-fxvector-length))

(provide s16vector->list)

(define (s16vector->list vec (start 0) (end (s16vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s16vector-ref vec i) list)))))

