#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in ffi/vector s32vector-length s32vector-ref))

(provide s32vector->list)

(define (s32vector->list vec (start 0) (end (s32vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s32vector-ref vec i) list)))))

