#lang racket/base
;;; Autogenerated on 2022-10-18T19:21:36
;;; DO NOT EDIT

(require (only-in ffi/vector s32vector-length s32vector-ref))

(require (only-in racket/unsafe/ops unsafe-bytes-length unsafe-flvector-length))

(provide s32vector->list)

(define (s32vector->list vec (start 0) (end (s32vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s32vector-ref vec i) list)))))

