#lang racket/base
;;; Autogenerated on 2022-10-18T19:21:36
;;; DO NOT EDIT

(require (only-in ffi/vector s64vector-length s64vector-ref))

(require (only-in racket/unsafe/ops unsafe-bytes-length unsafe-flvector-length))

(provide s64vector->list)

(define (s64vector->list vec (start 0) (end (s64vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s64vector-ref vec i) list)))))

