#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in ffi/vector s64vector-length s64vector-ref))

(provide s64vector->list)

(define (s64vector->list vec (start 0) (end (s64vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s64vector-ref vec i) list)))))

