#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 5:02:47pm
;;; DO NOT EDIT

(require (only-in ffi/vector s8vector-length s8vector-ref))

(provide s8vector->list)

(define (s8vector->list vec (start 0) (end (s8vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s8vector-ref vec i) list)))))

