#lang racket/base
;;; Autogenerated on 2022-10-25T17:34:11
;;; DO NOT EDIT

(require (only-in ffi/vector s8vector-length s8vector-ref))

(require (only-in
          racket/unsafe/ops
          unsafe-bytes-length
          unsafe-flvector-length
          unsafe-fxvector-length))

(provide s8vector->list)

(define (s8vector->list vec (start 0) (end (s8vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (s8vector-ref vec i) list)))))

