#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in ffi/vector u16vector-length u16vector-ref))

(provide u16vector->list)

(define (u16vector->list vec (start 0) (end (u16vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (u16vector-ref vec i) list)))))

