#lang racket/base
;;; Autogenerated on 2024-10-18T15:19:08
;;; DO NOT EDIT

(require (only-in ffi/vector u32vector-length u32vector-ref))

(require (only-in
          racket/unsafe/ops
          unsafe-bytes-length
          unsafe-flvector-length
          unsafe-fxvector-length))

(provide u32vector->list)

(define (u32vector->list vec (start 0) (end (u32vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (u32vector-ref vec i) list)))))

