#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 1:50:04am
;;; DO NOT EDIT

(require (only-in ffi/vector u32vector-length u32vector-ref))

(provide u32vector->list)

(define (u32vector->list vec (start 0) (end (u32vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (u32vector-ref vec i) list)))))

