#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 5:02:47pm
;;; DO NOT EDIT

(require (only-in ffi/vector u64vector-length u64vector-ref))

(provide u64vector->list)

(define (u64vector->list vec (start 0) (end (u64vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (u64vector-ref vec i) list)))))

