#lang racket/base
;;; Autogenerated on 2023-06-09T04:33:34
;;; DO NOT EDIT

(require (only-in ffi/vector u64vector-length u64vector-ref))

(require (only-in
          racket/unsafe/ops
          unsafe-bytes-length
          unsafe-flvector-length
          unsafe-fxvector-length))

(provide u64vector->list)

(define (u64vector->list vec (start 0) (end (u64vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (u64vector-ref vec i) list)))))

