#lang racket/base
;;; Autogenerated on 2023-10-07T16:04:06
;;; DO NOT EDIT

(require (only-in ffi/vector u8vector-length u8vector-ref))

(require (only-in
          racket/unsafe/ops
          unsafe-bytes-length
          unsafe-flvector-length
          unsafe-fxvector-length))

(provide u8vector->list)

(define (u8vector->list vec (start 0) (end (unsafe-bytes-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (u8vector-ref vec i) list)))))

