#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 10:42:27am
;;; DO NOT EDIT

(require (only-in ffi/vector u8vector-length u8vector-ref))

(provide u8vector->list)

(define (u8vector->list vec (start 0) (end (u8vector-length vec)))
  (let loop ((i (- end 1)) (list '()))
    (if (< i start) list (loop (- i 1) (cons (u8vector-ref vec i) list)))))

