#lang racket/base
;;; Autogenerated on 2022-10-25T17:34:11
;;; DO NOT EDIT

(require (only-in
          "base.rkt"
          c128?
          c128vector?
          c128vector
          make-c128vector
          c128vector-ref
          c128vector-set!
          c128vector-length
          c128vector->list
          list->c128vector)
         (only-in "../128.rkt" comparator? make-comparator)
         racket/contract
         racket/unsafe/ops)

(provide (all-from-out "base.rkt")
         c128vector-append-subvectors
         (contract-out
          (c128vector-unfold
           (-> procedure? exact-nonnegative-integer? any/c c128vector?))
          (c128vector-unfold-right
           (-> procedure? exact-nonnegative-integer? any/c c128vector?))
          (c128vector-copy
           (->*
            (c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            c128vector?))
          (c128vector-copy!
           (->*
            (c128vector? exact-nonnegative-integer? c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (c128vector-reverse-copy
           (->*
            (c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            c128vector?))
          (c128vector-reverse-copy!
           (->*
            (c128vector? exact-nonnegative-integer? c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (c128vector-append (-> c128vector? ... c128vector?))
          (c128vector-concatenate (-> (listof c128vector?) c128vector?))
          (c128vector-empty? (-> c128vector? boolean?))
          (c128vector= (-> c128vector? c128vector? c128vector? ... boolean?))
          (c128vector-take
           (-> c128vector? exact-nonnegative-integer? c128vector?))
          (c128vector-take-right
           (-> c128vector? exact-nonnegative-integer? c128vector?))
          (c128vector-drop
           (-> c128vector? exact-nonnegative-integer? c128vector?))
          (c128vector-drop-right
           (-> c128vector? exact-nonnegative-integer? c128vector?))
          (c128vector-segment
           (-> c128vector? exact-positive-integer? (listof c128vector?)))
          (c128vector-fold
           (-> procedure? any/c c128vector? c128vector? ... any/c))
          (c128vector-fold-right
           (-> procedure? any/c c128vector? c128vector? ... any/c))
          (c128vector-map
           (-> procedure? c128vector? c128vector? ... c128vector?))
          (c128vector-map!
           (-> procedure? c128vector? c128vector? ... c128vector?))
          (c128vector-for-each
           (-> procedure? c128vector? c128vector? ... void?))
          (c128vector-count
           (->
            procedure?
            c128vector?
            c128vector?
            ...
            exact-nonnegative-integer?))
          (c128vector-cumulate
           (-> (-> any/c c128? c128?) any/c c128vector? c128vector?))
          (c128vector-take-while (-> (-> c128? any/c) c128vector? c128vector?))
          (c128vector-take-while-right
           (-> (-> c128? any/c) c128vector? c128vector?))
          (c128vector-drop-while (-> (-> c128? any/c) c128vector? c128vector?))
          (c128vector-drop-while-right
           (-> (-> c128? any/c) c128vector? c128vector?))
          (c128vector-index
           (->
            procedure?
            c128vector?
            c128vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (c128vector-index-right
           (->
            procedure?
            c128vector?
            c128vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (c128vector-skip
           (->
            procedure?
            c128vector?
            c128vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (c128vector-skip-right
           (->
            procedure?
            c128vector?
            c128vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (c128vector-any (-> procedure? c128vector? c128vector? ... any))
          (c128vector-every (-> procedure? c128vector? c128vector? ... any))
          (c128vector-partition
           (->
            (-> c128? any/c)
            c128vector?
            (values c128vector? exact-nonnegative-integer?)))
          (c128vector-filter (-> (-> c128? any/c) c128vector? c128vector?))
          (c128vector-remove (-> (-> c128? any/c) c128vector? c128vector?))
          (c128vector-swap!
           (->
            c128vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            void?))
          (c128vector-fill!
           (->*
            (c128vector? c128?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (c128vector-reverse!
           (->*
            (c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (c128vector-unfold!
           (->
            (-> exact-nonnegative-integer? any/c (values c128? any/c))
            c128vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (c128vector-unfold-right!
           (->
            (-> exact-nonnegative-integer? any/c (values c128? any/c))
            c128vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (reverse-c128vector->list
           (->*
            (c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (listof c128?)))
          (reverse-list->c128vector (-> (listof c128?) c128vector?))
          (c128vector->vector
           (->*
            (c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (vectorof c128?)))
          (vector->c128vector
           (->*
            ((vectorof c128?))
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            c128vector?))
          (make-c128vector-generator
           (->*
            (c128vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (-> (or/c c128? eof-object?))))
          (write-c128vector (->* (c128vector?) (output-port?) void?))
          (c128vector-comparator comparator?)))

(define (c128vector-unfold f len seed)
  (let ((v (make-c128vector len)))
    (let loop ((i 0) (state seed))
      (unless (= i len)
        (let-values (((value newstate) (f i state)))
          (c128vector-set! v i value)
          (loop (+ i 1) newstate))))
    v))

(define (c128vector-unfold-right f len seed)
  (let ((v (make-c128vector len)))
    (let loop ((i (- len 1)) (state seed))
      (unless (= i -1)
        (let-values (((value newstate) (f i state)))
          (c128vector-set! v i value)
          (loop (- i 1) newstate))))
    v))

(define (c128vector-copy vec (start 0) (end (c128vector-length vec)))
  (let ((v (make-c128vector (- end start))))
    (c128vector-copy! v 0 vec start end)
    v))

(define (c128vector-copy! to at from (start 0) (end (c128vector-length from)))
  (let loop ((at at) (i start))
    (unless (= i end)
      (c128vector-set! to at (c128vector-ref from i))
      (loop (+ at 1) (+ i 1)))))

(define (c128vector-reverse-copy vec (start 0) (end (c128vector-length vec)))
  (let ((v (make-c128vector (- end start))))
    (c128vector-reverse-copy! v 0 vec start end)
    v))

(define (c128vector-reverse-copy!
         to
         at
         from
         (start 0)
         (end (c128vector-length from)))
  (let loop ((at at) (i (- end 1)))
    (unless (< i start)
      (c128vector-set! to at (c128vector-ref from i))
      (loop (+ at 1) (- i 1)))))

(define (c128vector-append . vecs) (c128vector-concatenate vecs))

(define (c128vector-concatenate vecs)
  (let ((v (make-c128vector (len-sum vecs))))
    (let loop ((vecs vecs) (at 0))
      (unless (null? vecs)
        (let ((vec (car vecs)))
          (c128vector-copy! v at vec 0 (c128vector-length vec))
          (loop (cdr vecs) (+ at (c128vector-length vec)))))
      v)))

(define (len-sum vecs)
  (if (null? vecs) 0 (+ (c128vector-length (car vecs)) (len-sum (cdr vecs)))))

(define (c128vector-append-subvectors . args)
  (let ((v (make-c128vector (len-subsum args))))
    (let loop ((args args) (at 0))
      (unless (null? args)
        (let ((vec (car args)) (start (cadr args)) (end (caddr args)))
          (c128vector-copy! v at vec start end)
          (loop (cdddr args) (+ at (- end start))))))
    v))

(define (len-subsum vecs)
  (if (null? vecs)
    0
    (+ (- (caddr vecs) (cadr vecs)) (len-subsum (cdddr vecs)))))

(define (c128vector-empty? vec) (zero? (c128vector-length vec)))

(define (c128vector= vec1 vec2 . vecs)
  (and (c128dyadic-vecs=
        vec1
        0
        (c128vector-length vec1)
        vec2
        0
        (c128vector-length vec2))
       (or (null? vecs)
           (null? (car vecs))
           (c128vector= vec2 (car vecs) (cdr vecs)))))

(define (c128dyadic-vecs= vec1 start1 end1 vec2 start2 end2)
  (cond
   ((not (= end1 end2)) #f)
   ((not (< start1 end1)) #t)
   ((let ((elt1 (c128vector-ref vec1 start1))
          (elt2 (c128vector-ref vec2 start2)))
      (= elt1 elt2))
    (c128dyadic-vecs= vec1 (+ start1 1) end1 vec2 (+ start2 1) end2))
   (else #f)))

(define (c128vector-take vec n)
  (let ((v (make-c128vector n))) (c128vector-copy! v 0 vec 0 n) v))

(define (c128vector-take-right vec n)
  (let ((v (make-c128vector n)) (len (c128vector-length vec)))
    (c128vector-copy! v 0 vec (- len n) len)
    v))

(define (c128vector-drop vec n)
  (let* ((len (c128vector-length vec))
         (vlen (- len n))
         (v (make-c128vector vlen)))
    (c128vector-copy! v 0 vec n len)
    v))

(define (c128vector-drop-right vec n)
  (let* ((len (c128vector-length vec))
         (rlen (- len n))
         (v (make-c128vector rlen)))
    (c128vector-copy! v 0 vec 0 rlen)
    v))

(define (c128vector-segment vec n)
  (let loop ((r '()) (i 0) (remain (c128vector-length vec)))
    (if (<= remain 0)
      (reverse r)
      (let ((size (min n remain)))
        (loop
         (cons (c128vector-copy vec i (+ i size)) r)
         (+ i size)
         (- remain size))))))

(define (%c128vectors-ref vecs i) (map (lambda (v) (c128vector-ref v i)) vecs))

(define (c128vector-fold kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((r knil) (i 0))
        (if (= i len) r (loop (kons r (c128vector-ref vec i)) (+ i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((r knil) (i 0))
        (if (= i len)
          r
          (loop (apply kons r (%c128vectors-ref vecs i)) (+ i 1)))))))

(define (c128vector-fold-right kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((r knil) (i (- (c128vector-length vec) 1)))
        (if (negative? i) r (loop (kons r (c128vector-ref vec i)) (- i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((r knil) (i (- len 1)))
        (if (negative? i)
          r
          (loop (apply kons r (%c128vectors-ref vecs i)) (- i 1)))))))

(define (c128vector-map f vec . vecs)
  (if (null? vecs)
    (let* ((len (c128vector-length vec)) (v (make-c128vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (c128vector-set! v i (f (c128vector-ref vec i)))
          (loop (+ i 1))))
      v)
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs)))
           (v (make-c128vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (c128vector-set! v i (apply f (%c128vectors-ref vecs i)))
          (loop (+ i 1))))
      v)))

(define (c128vector-map! f vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((i 0))
        (unless (= i len)
          (c128vector-set! vec i (f (c128vector-ref vec i)))
          (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len)
          (c128vector-set! vec i (apply f (%c128vectors-ref vecs i)))
          (loop (+ i 1)))))))

(define (c128vector-for-each f vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((i 0))
        (unless (= i len) (f (c128vector-ref vec i)) (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len)
          (apply f (%c128vectors-ref vecs i))
          (loop (+ i 1)))))))

(define (c128vector-count pred vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((i 0) (r 0))
        (cond
         ((= i (c128vector-length vec)) r)
         ((pred (c128vector-ref vec i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((i 0) (r 0))
        (cond
         ((= i len) r)
         ((apply pred (%c128vectors-ref vecs i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))))

(define (c128vector-cumulate f knil vec)
  (let* ((len (c128vector-length vec)) (v (make-c128vector len)))
    (let loop ((r knil) (i 0))
      (unless (= i len)
        (let ((next (f r (c128vector-ref vec i))))
          (c128vector-set! v i next)
          (loop next (+ i 1)))))
    v))

(define (c128vector-take-while pred vec)
  (let* ((len (c128vector-length vec))
         (idx (c128vector-skip pred vec))
         (idx* (if idx idx len)))
    (c128vector-copy vec 0 idx*)))

(define (c128vector-take-while-right pred vec)
  (let* ((len (c128vector-length vec))
         (idx (c128vector-skip-right pred vec))
         (idx* (if idx (+ idx 1) 0)))
    (c128vector-copy vec idx* len)))

(define (c128vector-drop-while pred vec)
  (let* ((len (c128vector-length vec))
         (idx (c128vector-skip pred vec))
         (idx* (if idx idx len)))
    (c128vector-copy vec idx* len)))

(define (c128vector-drop-while-right pred vec)
  (let* ((len (c128vector-length vec))
         (idx (c128vector-skip-right pred vec))
         (idx* (if idx idx -1)))
    (c128vector-copy vec 0 (+ 1 idx*))))

(define (c128vector-index pred vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (c128vector-ref vec i)) i)
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%c128vectors-ref vecs i)) i)
         (else (loop (+ i 1))))))))

(define (c128vector-index-right pred vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((pred (c128vector-ref vec i)) i)
         (else (loop (- i 1))))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((apply pred (%c128vectors-ref vecs i)) i)
         (else (loop (- i 1))))))))

(define (c128vector-skip pred vec . vecs)
  (if (null? vecs)
    (c128vector-index (lambda (x) (not (pred x))) vec)
    (apply c128vector-index (lambda xs (not (apply pred xs))) vec vecs)))

(define (c128vector-skip-right pred vec . vecs)
  (if (null? vecs)
    (c128vector-index-right (lambda (x) (not (pred x))) vec)
    (apply c128vector-index-right (lambda xs (not (apply pred xs))) vec vecs)))

(define (c128vector-any pred vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (c128vector-ref vec i)))
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%c128vectors-ref vecs i)))
         (else (loop (+ i 1))))))))

(define (c128vector-every pred vec . vecs)
  (if (null? vecs)
    (let ((len (c128vector-length vec)))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((pred (c128vector-ref vec i)) => (lambda (r) (loop (+ i 1) r)))
         (else #f))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map c128vector-length vecs))))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((apply pred (%c128vectors-ref vecs i))
          =>
          (lambda (r) (loop (+ i 1) r)))
         (else #f))))))

(define (c128vector-partition pred vec)
  (let* ((len (c128vector-length vec))
         (cnt (c128vector-count pred vec))
         (r (make-c128vector len)))
    (let loop ((i 0) (yes 0) (no cnt))
      (cond
       ((= i len) r)
       ((pred (c128vector-ref vec i))
        (c128vector-set! r yes (c128vector-ref vec i))
        (loop (+ i 1) (+ yes 1) no))
       (else
        (c128vector-set! r no (c128vector-ref vec i))
        (loop (+ i 1) yes (+ no 1)))))))

(define (c128vector-filter pred vec)
  (let* ((len (c128vector-length vec))
         (cnt (c128vector-count pred vec))
         (r (make-c128vector cnt)))
    (let loop ((i 0) (j 0))
      (cond
       ((= i len) r)
       ((pred (c128vector-ref vec i))
        (c128vector-set! r j (c128vector-ref vec i))
        (loop (+ i 1) (+ j 1)))
       (else (loop (+ i 1) j))))))

(define (c128vector-remove pred vec)
  (c128vector-filter (lambda (x) (not (pred x))) vec))

(define (c128vector-swap! vec i j)
  (let ((ival (c128vector-ref vec i)) (jval (c128vector-ref vec j)))
    (c128vector-set! vec i jval)
    (c128vector-set! vec j ival)))

(define (c128vector-fill! vec fill (start 0) (end (c128vector-length vec)))
  (unless (= start end)
    (c128vector-set! vec start fill)
    (c128vector-fill! vec fill (+ start 1) end)))

(define (c128vector-reverse! vec (start 0) (end (c128vector-length vec)))
  (let loop ((i start) (j (- end 1)))
    (when (< i j) (c128vector-swap! vec i j) (loop (+ i 1) (- j 1)))))

(define (c128vector-unfold! f vec start end seed)
  (let loop ((i start) (seed seed))
    (when (< i end)
      (let-values (((elt seed) (f i seed)))
        (c128vector-set! vec i elt)
        (loop (+ i 1) seed)))))

(define (c128vector-unfold-right! f vec start end seed)
  (let loop ((i (- end 1)) (seed seed))
    (when (>= i start)
      (let-values (((elt seed) (f i seed)))
        (c128vector-set! vec i elt)
        (loop (- i 1) seed)))))

(define (reverse-c128vector->list vec (start 0) (end (c128vector-length vec)))
  (let loop ((i start) (r '()))
    (if (= i end) r (loop (+ 1 i) (cons (c128vector-ref vec i) r)))))

(define (reverse-list->c128vector list)
  (let* ((len (length list)) (r (make-c128vector len)))
    (let loop ((i 0) (list list))
      (cond
       ((= i len) r)
       (else
        (c128vector-set! r (- len i 1) (car list))
        (loop (+ i 1) (cdr list)))))))

(define (c128vector->vector vec (start 0) (end (c128vector-length vec)))
  (let* ((len (- end start)) (r (make-vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else
        (vector-set! r o (c128vector-ref vec i))
        (loop (+ i 1) (+ o 1)))))))

(define (vector->c128vector vec (start 0) (end (vector-length vec)))
  (let* ((len (- end start)) (r (make-c128vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else
        (c128vector-set! r o (vector-ref vec i))
        (loop (+ i 1) (+ o 1)))))))

(define (make-c128vector-generator vec (start 0) (end (c128vector-length vec)))
  (lambda ()
    (if (>= start end)
      eof
      (let ((next (c128vector-ref vec start))) (set! start (+ start 1)) next))))

(define (write-c128vector vec (port (current-output-port)))
  (begin
    (fprintf port "#~A(" 'c128)
    (let ((last (- (c128vector-length vec) 1)))
      (let loop ((i 0))
        (cond
         ((= i last) (write (c128vector-ref vec i) port) (display ")" port))
         (else
          (write (c128vector-ref vec i) port)
          (display " " port)
          (loop (+ i 1))))))))

(define (c128vector< vec1 vec2)
  (let ((len1 (c128vector-length vec1)) (len2 (c128vector-length vec2)))
    (cond
     ((< len1 len2) #t)
     ((> len1 len2) #f)
     (else
      (let loop ((i 0))
        (cond
         ((= i len1) #f)
         ((< (c128vector-ref vec1 i) (c128vector-ref vec2 i)) #t)
         ((> (c128vector-ref vec1 i) (c128vector-ref vec2 i)) #f)
         (else (loop (+ i 1)))))))))

(define (c128vector-hash vec)
  (let ((len (min 256 (c128vector-length vec))))
    (let loop ((i 0) (r 0))
      (if (= i len)
        (abs (floor (real-part (inexact->exact r))))
        (loop (+ i 1) (+ r (c128vector-ref vec i)))))))

(define c128vector-comparator
  (make-comparator c128vector? c128vector= c128vector< c128vector-hash))

