#lang racket/base
;;; Autogenerated on 2023-10-07T16:04:06
;;; DO NOT EDIT

(require (only-in
          "base.rkt"
          f32?
          f32vector?
          f32vector
          make-f32vector
          f32vector-ref
          f32vector-set!
          f32vector-length
          f32vector->list
          list->f32vector)
         (only-in "../128.rkt" comparator? make-comparator)
         racket/contract
         racket/unsafe/ops)

(provide (all-from-out "base.rkt")
         f32vector-append-subvectors
         (contract-out
          (f32vector-unfold
           (-> procedure? exact-nonnegative-integer? any/c f32vector?))
          (f32vector-unfold-right
           (-> procedure? exact-nonnegative-integer? any/c f32vector?))
          (f32vector-copy
           (->*
            (f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            f32vector?))
          (f32vector-copy!
           (->*
            (f32vector? exact-nonnegative-integer? f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (f32vector-reverse-copy
           (->*
            (f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            f32vector?))
          (f32vector-reverse-copy!
           (->*
            (f32vector? exact-nonnegative-integer? f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (f32vector-append (-> f32vector? ... f32vector?))
          (f32vector-concatenate (-> (listof f32vector?) f32vector?))
          (f32vector-empty? (-> f32vector? boolean?))
          (f32vector= (-> f32vector? f32vector? f32vector? ... boolean?))
          (f32vector-take (-> f32vector? exact-nonnegative-integer? f32vector?))
          (f32vector-take-right
           (-> f32vector? exact-nonnegative-integer? f32vector?))
          (f32vector-drop (-> f32vector? exact-nonnegative-integer? f32vector?))
          (f32vector-drop-right
           (-> f32vector? exact-nonnegative-integer? f32vector?))
          (f32vector-segment
           (-> f32vector? exact-positive-integer? (listof f32vector?)))
          (f32vector-fold
           (->i
            ((kons
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 2)))))
             (knil any/c)
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ any/c)))
          (f32vector-fold-right
           (->i
            ((kons
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 2)))))
             (knil any/c)
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ any/c)))
          (f32vector-map
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> f32?)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ f32vector?)))
          (f32vector-map!
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> f32?)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ f32vector?)))
          (f32vector-for-each
           (->i
            ((proc
              (vecs)
              (lambda (f)
                (and (procedure? f)
                     (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ void?)))
          (f32vector-count
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ exact-nonnegative-integer?)))
          (f32vector-cumulate
           (-> (-> any/c f32? f32?) any/c f32vector? f32vector?))
          (f32vector-take-while (-> (-> f32? any/c) f32vector? f32vector?))
          (f32vector-take-while-right
           (-> (-> f32? any/c) f32vector? f32vector?))
          (f32vector-drop-while (-> (-> f32? any/c) f32vector? f32vector?))
          (f32vector-drop-while-right
           (-> (-> f32? any/c) f32vector? f32vector?))
          (f32vector-index
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (f32vector-index-right
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (f32vector-skip
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (f32vector-skip-right
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (f32vector-any
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ any/c)))
          (f32vector-every
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 f32vector?))
            ()
            #:rest
            (vecs (listof f32vector?))
            (_ any/c)))
          (f32vector-partition
           (->
            (-> f32? any/c)
            f32vector?
            (values f32vector? exact-nonnegative-integer?)))
          (f32vector-filter (-> (-> f32? any/c) f32vector? f32vector?))
          (f32vector-remove (-> (-> f32? any/c) f32vector? f32vector?))
          (f32vector-swap!
           (->
            f32vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            void?))
          (f32vector-fill!
           (->*
            (f32vector? f32?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (f32vector-reverse!
           (->*
            (f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (f32vector-unfold!
           (->
            (-> exact-nonnegative-integer? any/c (values f32? any/c))
            f32vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (f32vector-unfold-right!
           (->
            (-> exact-nonnegative-integer? any/c (values f32? any/c))
            f32vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (reverse-f32vector->list
           (->*
            (f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (listof f32?)))
          (reverse-list->f32vector (-> (listof f32?) f32vector?))
          (f32vector->vector
           (->*
            (f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (vectorof f32?)))
          (vector->f32vector
           (->*
            ((vectorof f32?))
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            f32vector?))
          (make-f32vector-generator
           (->*
            (f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (-> (or/c f32? eof-object?))))
          (write-f32vector (->* (f32vector?) (output-port?) void?))
          (f32vector-comparator comparator?)
          (in-f32vector
           (->*
            (f32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            sequence?))))

(module+
 unsafe
 (require (only-in
           (submod "base.rkt" unsafe)
           f32?
           f32vector?
           f32vector
           make-f32vector
           f32vector-ref
           f32vector-set!
           f32vector-length
           f32vector->list
           list->f32vector))
 (provide (all-from-out (submod "base.rkt" unsafe))
          f32vector-unfold
          f32vector-unfold-right
          f32vector-copy
          f32vector-copy!
          f32vector-reverse-copy
          f32vector-reverse-copy!
          f32vector-append
          f32vector-concatenate
          f32vector-empty?
          f32vector=
          f32vector-take
          f32vector-take-right
          f32vector-drop
          f32vector-drop-right
          f32vector-segment
          f32vector-fold
          f32vector-fold-right
          f32vector-map
          f32vector-map!
          f32vector-for-each
          f32vector-count
          f32vector-cumulate
          f32vector-take-while
          f32vector-take-while-right
          f32vector-drop-while
          f32vector-drop-while-right
          f32vector-index
          f32vector-index-right
          f32vector-skip
          f32vector-skip-right
          f32vector-any
          f32vector-every
          f32vector-partition
          f32vector-filter
          f32vector-remove
          f32vector-swap!
          f32vector-fill!
          f32vector-reverse!
          f32vector-unfold!
          f32vector-unfold-right!
          reverse-f32vector->list
          f32vector->vector
          make-f32vector-generator
          write-f32vector
          f32vector-comparator
          f32vector-append-subvectors
          in-f32vector))

(define (f32vector-unfold f len seed)
  (let ((v (make-f32vector len)))
    (let loop ((i 0) (state seed))
      (unless (= i len)
        (let-values (((value newstate) (f i state)))
          (f32vector-set! v i value)
          (loop (+ i 1) newstate))))
    v))

(define (f32vector-unfold-right f len seed)
  (let ((v (make-f32vector len)))
    (let loop ((i (- len 1)) (state seed))
      (unless (= i -1)
        (let-values (((value newstate) (f i state)))
          (f32vector-set! v i value)
          (loop (- i 1) newstate))))
    v))

(define (f32vector-copy vec (start 0) (end (f32vector-length vec)))
  (let ((v (make-f32vector (- end start))))
    (f32vector-copy! v 0 vec start end)
    v))

(define (f32vector-copy! to at from (start 0) (end (f32vector-length from)))
  (let loop ((at at) (i start))
    (unless (= i end)
      (f32vector-set! to at (f32vector-ref from i))
      (loop (+ at 1) (+ i 1)))))

(define (f32vector-reverse-copy vec (start 0) (end (f32vector-length vec)))
  (let ((v (make-f32vector (- end start))))
    (f32vector-reverse-copy! v 0 vec start end)
    v))

(define (f32vector-reverse-copy!
         to
         at
         from
         (start 0)
         (end (f32vector-length from)))
  (let loop ((at at) (i (- end 1)))
    (unless (< i start)
      (f32vector-set! to at (f32vector-ref from i))
      (loop (+ at 1) (- i 1)))))

(define (f32vector-append . vecs) (f32vector-concatenate vecs))

(define (f32vector-concatenate vecs)
  (let ((v (make-f32vector (len-sum vecs))))
    (let loop ((vecs vecs) (at 0))
      (unless (null? vecs)
        (let ((vec (car vecs)))
          (f32vector-copy! v at vec 0 (f32vector-length vec))
          (loop (cdr vecs) (+ at (f32vector-length vec)))))
      v)))

(define (len-sum vecs)
  (if (null? vecs) 0 (+ (f32vector-length (car vecs)) (len-sum (cdr vecs)))))

(define (f32vector-append-subvectors . args)
  (let ((v (make-f32vector (len-subsum args))))
    (let loop ((args args) (at 0))
      (unless (null? args)
        (let ((vec (car args)) (start (cadr args)) (end (caddr args)))
          (f32vector-copy! v at vec start end)
          (loop (cdddr args) (+ at (- end start))))))
    v))

(define (len-subsum vecs)
  (if (null? vecs)
    0
    (+ (- (caddr vecs) (cadr vecs)) (len-subsum (cdddr vecs)))))

(define (f32vector-empty? vec) (zero? (f32vector-length vec)))

(define (f32vector= vec1 vec2 . vecs)
  (and (f32dyadic-vecs=
        vec1
        0
        (f32vector-length vec1)
        vec2
        0
        (f32vector-length vec2))
       (or (null? vecs)
           (null? (car vecs))
           (f32vector= vec2 (car vecs) (cdr vecs)))))

(define (f32dyadic-vecs= vec1 start1 end1 vec2 start2 end2)
  (cond
   ((not (= end1 end2)) #f)
   ((not (< start1 end1)) #t)
   ((let ((elt1 (f32vector-ref vec1 start1)) (elt2 (f32vector-ref vec2 start2)))
      (= elt1 elt2))
    (f32dyadic-vecs= vec1 (+ start1 1) end1 vec2 (+ start2 1) end2))
   (else #f)))

(define (f32vector-take vec n)
  (let ((v (make-f32vector n))) (f32vector-copy! v 0 vec 0 n) v))

(define (f32vector-take-right vec n)
  (let ((v (make-f32vector n)) (len (f32vector-length vec)))
    (f32vector-copy! v 0 vec (- len n) len)
    v))

(define (f32vector-drop vec n)
  (let* ((len (f32vector-length vec))
         (vlen (- len n))
         (v (make-f32vector vlen)))
    (f32vector-copy! v 0 vec n len)
    v))

(define (f32vector-drop-right vec n)
  (let* ((len (f32vector-length vec))
         (rlen (- len n))
         (v (make-f32vector rlen)))
    (f32vector-copy! v 0 vec 0 rlen)
    v))

(define (f32vector-segment vec n)
  (let loop ((r '()) (i 0) (remain (f32vector-length vec)))
    (if (<= remain 0)
      (reverse r)
      (let ((size (min n remain)))
        (loop
         (cons (f32vector-copy vec i (+ i size)) r)
         (+ i size)
         (- remain size))))))

(define (%f32vectors-ref vecs i) (map (lambda (v) (f32vector-ref v i)) vecs))

(define (f32vector-fold kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((r knil) (i 0))
        (if (= i len) r (loop (kons r (f32vector-ref vec i)) (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((r knil) (i 0))
        (if (= i len)
          r
          (loop (apply kons r (%f32vectors-ref vecs i)) (+ i 1)))))))

(define (f32vector-fold-right kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((r knil) (i (- (f32vector-length vec) 1)))
        (if (negative? i) r (loop (kons r (f32vector-ref vec i)) (- i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((r knil) (i (- len 1)))
        (if (negative? i)
          r
          (loop (apply kons r (%f32vectors-ref vecs i)) (- i 1)))))))

(define (f32vector-map f vec . vecs)
  (if (null? vecs)
    (let* ((len (f32vector-length vec)) (v (make-f32vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (f32vector-set! v i (f (f32vector-ref vec i)))
          (loop (+ i 1))))
      v)
    (let* ((vecs (cons vec vecs))
           (len (apply min (map f32vector-length vecs)))
           (v (make-f32vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (f32vector-set! v i (apply f (%f32vectors-ref vecs i)))
          (loop (+ i 1))))
      v)))

(define (f32vector-map! f vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((i 0))
        (unless (= i len)
          (f32vector-set! vec i (f (f32vector-ref vec i)))
          (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len)
          (f32vector-set! vec i (apply f (%f32vectors-ref vecs i)))
          (loop (+ i 1)))))))

(define (f32vector-for-each f vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((i 0))
        (unless (= i len) (f (f32vector-ref vec i)) (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len) (apply f (%f32vectors-ref vecs i)) (loop (+ i 1)))))))

(define (f32vector-count pred vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((i 0) (r 0))
        (cond
         ((= i (f32vector-length vec)) r)
         ((pred (f32vector-ref vec i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((i 0) (r 0))
        (cond
         ((= i len) r)
         ((apply pred (%f32vectors-ref vecs i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))))

(define (f32vector-cumulate f knil vec)
  (let* ((len (f32vector-length vec)) (v (make-f32vector len)))
    (let loop ((r knil) (i 0))
      (unless (= i len)
        (let ((next (f r (f32vector-ref vec i))))
          (f32vector-set! v i next)
          (loop next (+ i 1)))))
    v))

(define (f32vector-take-while pred vec)
  (let* ((len (f32vector-length vec))
         (idx (f32vector-skip pred vec))
         (idx* (if idx idx len)))
    (f32vector-copy vec 0 idx*)))

(define (f32vector-take-while-right pred vec)
  (let* ((len (f32vector-length vec))
         (idx (f32vector-skip-right pred vec))
         (idx* (if idx (+ idx 1) 0)))
    (f32vector-copy vec idx* len)))

(define (f32vector-drop-while pred vec)
  (let* ((len (f32vector-length vec))
         (idx (f32vector-skip pred vec))
         (idx* (if idx idx len)))
    (f32vector-copy vec idx* len)))

(define (f32vector-drop-while-right pred vec)
  (let* ((len (f32vector-length vec))
         (idx (f32vector-skip-right pred vec))
         (idx* (if idx idx -1)))
    (f32vector-copy vec 0 (+ 1 idx*))))

(define (f32vector-index pred vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (f32vector-ref vec i)) i)
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%f32vectors-ref vecs i)) i)
         (else (loop (+ i 1))))))))

(define (f32vector-index-right pred vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((pred (f32vector-ref vec i)) i)
         (else (loop (- i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((apply pred (%f32vectors-ref vecs i)) i)
         (else (loop (- i 1))))))))

(define (f32vector-skip pred vec . vecs)
  (if (null? vecs)
    (f32vector-index (lambda (x) (not (pred x))) vec)
    (apply f32vector-index (lambda xs (not (apply pred xs))) vec vecs)))

(define (f32vector-skip-right pred vec . vecs)
  (if (null? vecs)
    (f32vector-index-right (lambda (x) (not (pred x))) vec)
    (apply f32vector-index-right (lambda xs (not (apply pred xs))) vec vecs)))

(define (f32vector-any pred vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (f32vector-ref vec i)))
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%f32vectors-ref vecs i)))
         (else (loop (+ i 1))))))))

(define (f32vector-every pred vec . vecs)
  (if (null? vecs)
    (let ((len (f32vector-length vec)))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((pred (f32vector-ref vec i)) => (lambda (r) (loop (+ i 1) r)))
         (else #f))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map f32vector-length vecs))))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((apply pred (%f32vectors-ref vecs i))
          =>
          (lambda (r) (loop (+ i 1) r)))
         (else #f))))))

(define (f32vector-partition pred vec)
  (let* ((len (f32vector-length vec))
         (cnt (f32vector-count pred vec))
         (r (make-f32vector len)))
    (let loop ((i 0) (yes 0) (no cnt))
      (cond
       ((= i len) (values r cnt))
       ((pred (f32vector-ref vec i))
        (f32vector-set! r yes (f32vector-ref vec i))
        (loop (+ i 1) (+ yes 1) no))
       (else
        (f32vector-set! r no (f32vector-ref vec i))
        (loop (+ i 1) yes (+ no 1)))))))

(define (f32vector-filter pred vec)
  (let* ((len (f32vector-length vec))
         (cnt (f32vector-count pred vec))
         (r (make-f32vector cnt)))
    (let loop ((i 0) (j 0))
      (cond
       ((= i len) r)
       ((pred (f32vector-ref vec i))
        (f32vector-set! r j (f32vector-ref vec i))
        (loop (+ i 1) (+ j 1)))
       (else (loop (+ i 1) j))))))

(define (f32vector-remove pred vec)
  (f32vector-filter (lambda (x) (not (pred x))) vec))

(define (f32vector-swap! vec i j)
  (let ((ival (f32vector-ref vec i)) (jval (f32vector-ref vec j)))
    (f32vector-set! vec i jval)
    (f32vector-set! vec j ival)))

(define (f32vector-fill! vec fill (start 0) (end (f32vector-length vec)))
  (unless (= start end)
    (f32vector-set! vec start fill)
    (f32vector-fill! vec fill (+ start 1) end)))

(define (f32vector-reverse! vec (start 0) (end (f32vector-length vec)))
  (let loop ((i start) (j (- end 1)))
    (when (< i j) (f32vector-swap! vec i j) (loop (+ i 1) (- j 1)))))

(define (f32vector-unfold! f vec start end seed)
  (let loop ((i start) (seed seed))
    (when (< i end)
      (let-values (((elt seed) (f i seed)))
        (f32vector-set! vec i elt)
        (loop (+ i 1) seed)))))

(define (f32vector-unfold-right! f vec start end seed)
  (let loop ((i (- end 1)) (seed seed))
    (when (>= i start)
      (let-values (((elt seed) (f i seed)))
        (f32vector-set! vec i elt)
        (loop (- i 1) seed)))))

(define (reverse-f32vector->list vec (start 0) (end (f32vector-length vec)))
  (let loop ((i start) (r '()))
    (if (= i end) r (loop (+ 1 i) (cons (f32vector-ref vec i) r)))))

(define (reverse-list->f32vector list)
  (let* ((len (length list)) (r (make-f32vector len)))
    (let loop ((i 0) (list list))
      (cond
       ((= i len) r)
       (else
        (f32vector-set! r (- len i 1) (car list))
        (loop (+ i 1) (cdr list)))))))

(define (f32vector->vector vec (start 0) (end (f32vector-length vec)))
  (let* ((len (- end start)) (r (make-vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (vector-set! r o (f32vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (vector->f32vector vec (start 0) (end (vector-length vec)))
  (let* ((len (- end start)) (r (make-f32vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (f32vector-set! r o (vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (make-f32vector-generator vec (start 0) (end (f32vector-length vec)))
  (lambda ()
    (if (>= start end)
      eof
      (let ((next (f32vector-ref vec start))) (set! start (+ start 1)) next))))

(define (write-f32vector vec (port (current-output-port)))
  (begin
    (fprintf port "#~A(" 'f32)
    (let ((last (- (f32vector-length vec) 1)))
      (let loop ((i 0))
        (cond
         ((= i last) (write (f32vector-ref vec i) port) (display ")" port))
         (else
          (write (f32vector-ref vec i) port)
          (display " " port)
          (loop (+ i 1))))))))

(define (f32vector< vec1 vec2)
  (let ((len1 (f32vector-length vec1)) (len2 (f32vector-length vec2)))
    (cond
     ((< len1 len2) #t)
     ((> len1 len2) #f)
     (else
      (let loop ((i 0))
        (cond
         ((= i len1) #f)
         ((< (f32vector-ref vec1 i) (f32vector-ref vec2 i)) #t)
         ((> (f32vector-ref vec1 i) (f32vector-ref vec2 i)) #f)
         (else (loop (+ i 1)))))))))

(define (f32vector-hash vec)
  (let ((len (min 256 (f32vector-length vec))))
    (let loop ((i 0) (r 0))
      (if (= i len)
        (abs (floor (real-part (inexact->exact r))))
        (loop (+ i 1) (+ r (f32vector-ref vec i)))))))

(define f32vector-comparator
  (make-comparator f32vector? f32vector= f32vector< f32vector-hash))

(define (in-f32vector vec (start 0) (end (f32vector-length vec)))
  (make-do-sequence
   (lambda ()
     (values
      (lambda (i) (f32vector-ref vec i))
      #f
      add1
      start
      (lambda (i) (< i end))
      #f
      #f))))

