#lang racket/base
;;; Autogenerated on 2022-10-25T17:34:11
;;; DO NOT EDIT

(require (only-in
          "base.rkt"
          s32?
          s32vector?
          s32vector
          make-s32vector
          s32vector-ref
          s32vector-set!
          s32vector-length
          s32vector->list
          list->s32vector)
         (only-in "../128.rkt" comparator? make-comparator)
         racket/contract
         racket/unsafe/ops)

(provide (all-from-out "base.rkt")
         s32vector-append-subvectors
         (contract-out
          (s32vector-unfold
           (-> procedure? exact-nonnegative-integer? any/c s32vector?))
          (s32vector-unfold-right
           (-> procedure? exact-nonnegative-integer? any/c s32vector?))
          (s32vector-copy
           (->*
            (s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            s32vector?))
          (s32vector-copy!
           (->*
            (s32vector? exact-nonnegative-integer? s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s32vector-reverse-copy
           (->*
            (s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            s32vector?))
          (s32vector-reverse-copy!
           (->*
            (s32vector? exact-nonnegative-integer? s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s32vector-append (-> s32vector? ... s32vector?))
          (s32vector-concatenate (-> (listof s32vector?) s32vector?))
          (s32vector-empty? (-> s32vector? boolean?))
          (s32vector= (-> s32vector? s32vector? s32vector? ... boolean?))
          (s32vector-take (-> s32vector? exact-nonnegative-integer? s32vector?))
          (s32vector-take-right
           (-> s32vector? exact-nonnegative-integer? s32vector?))
          (s32vector-drop (-> s32vector? exact-nonnegative-integer? s32vector?))
          (s32vector-drop-right
           (-> s32vector? exact-nonnegative-integer? s32vector?))
          (s32vector-segment
           (-> s32vector? exact-positive-integer? (listof s32vector?)))
          (s32vector-fold (-> procedure? any/c s32vector? s32vector? ... any/c))
          (s32vector-fold-right
           (-> procedure? any/c s32vector? s32vector? ... any/c))
          (s32vector-map (-> procedure? s32vector? s32vector? ... s32vector?))
          (s32vector-map! (-> procedure? s32vector? s32vector? ... s32vector?))
          (s32vector-for-each (-> procedure? s32vector? s32vector? ... void?))
          (s32vector-count
           (-> procedure? s32vector? s32vector? ... exact-nonnegative-integer?))
          (s32vector-cumulate
           (-> (-> any/c s32? s32?) any/c s32vector? s32vector?))
          (s32vector-take-while (-> (-> s32? any/c) s32vector? s32vector?))
          (s32vector-take-while-right
           (-> (-> s32? any/c) s32vector? s32vector?))
          (s32vector-drop-while (-> (-> s32? any/c) s32vector? s32vector?))
          (s32vector-drop-while-right
           (-> (-> s32? any/c) s32vector? s32vector?))
          (s32vector-index
           (->
            procedure?
            s32vector?
            s32vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s32vector-index-right
           (->
            procedure?
            s32vector?
            s32vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s32vector-skip
           (->
            procedure?
            s32vector?
            s32vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s32vector-skip-right
           (->
            procedure?
            s32vector?
            s32vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s32vector-any (-> procedure? s32vector? s32vector? ... any))
          (s32vector-every (-> procedure? s32vector? s32vector? ... any))
          (s32vector-partition
           (->
            (-> s32? any/c)
            s32vector?
            (values s32vector? exact-nonnegative-integer?)))
          (s32vector-filter (-> (-> s32? any/c) s32vector? s32vector?))
          (s32vector-remove (-> (-> s32? any/c) s32vector? s32vector?))
          (s32vector-swap!
           (->
            s32vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            void?))
          (s32vector-fill!
           (->*
            (s32vector? s32?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s32vector-reverse!
           (->*
            (s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s32vector-unfold!
           (->
            (-> exact-nonnegative-integer? any/c (values s32? any/c))
            s32vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (s32vector-unfold-right!
           (->
            (-> exact-nonnegative-integer? any/c (values s32? any/c))
            s32vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (reverse-s32vector->list
           (->*
            (s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (listof s32?)))
          (reverse-list->s32vector (-> (listof s32?) s32vector?))
          (s32vector->vector
           (->*
            (s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (vectorof s32?)))
          (vector->s32vector
           (->*
            ((vectorof s32?))
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            s32vector?))
          (make-s32vector-generator
           (->*
            (s32vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (-> (or/c s32? eof-object?))))
          (write-s32vector (->* (s32vector?) (output-port?) void?))
          (s32vector-comparator comparator?)))

(define (s32vector-unfold f len seed)
  (let ((v (make-s32vector len)))
    (let loop ((i 0) (state seed))
      (unless (= i len)
        (let-values (((value newstate) (f i state)))
          (s32vector-set! v i value)
          (loop (+ i 1) newstate))))
    v))

(define (s32vector-unfold-right f len seed)
  (let ((v (make-s32vector len)))
    (let loop ((i (- len 1)) (state seed))
      (unless (= i -1)
        (let-values (((value newstate) (f i state)))
          (s32vector-set! v i value)
          (loop (- i 1) newstate))))
    v))

(define (s32vector-copy vec (start 0) (end (s32vector-length vec)))
  (let ((v (make-s32vector (- end start))))
    (s32vector-copy! v 0 vec start end)
    v))

(define (s32vector-copy! to at from (start 0) (end (s32vector-length from)))
  (let loop ((at at) (i start))
    (unless (= i end)
      (s32vector-set! to at (s32vector-ref from i))
      (loop (+ at 1) (+ i 1)))))

(define (s32vector-reverse-copy vec (start 0) (end (s32vector-length vec)))
  (let ((v (make-s32vector (- end start))))
    (s32vector-reverse-copy! v 0 vec start end)
    v))

(define (s32vector-reverse-copy!
         to
         at
         from
         (start 0)
         (end (s32vector-length from)))
  (let loop ((at at) (i (- end 1)))
    (unless (< i start)
      (s32vector-set! to at (s32vector-ref from i))
      (loop (+ at 1) (- i 1)))))

(define (s32vector-append . vecs) (s32vector-concatenate vecs))

(define (s32vector-concatenate vecs)
  (let ((v (make-s32vector (len-sum vecs))))
    (let loop ((vecs vecs) (at 0))
      (unless (null? vecs)
        (let ((vec (car vecs)))
          (s32vector-copy! v at vec 0 (s32vector-length vec))
          (loop (cdr vecs) (+ at (s32vector-length vec)))))
      v)))

(define (len-sum vecs)
  (if (null? vecs) 0 (+ (s32vector-length (car vecs)) (len-sum (cdr vecs)))))

(define (s32vector-append-subvectors . args)
  (let ((v (make-s32vector (len-subsum args))))
    (let loop ((args args) (at 0))
      (unless (null? args)
        (let ((vec (car args)) (start (cadr args)) (end (caddr args)))
          (s32vector-copy! v at vec start end)
          (loop (cdddr args) (+ at (- end start))))))
    v))

(define (len-subsum vecs)
  (if (null? vecs)
    0
    (+ (- (caddr vecs) (cadr vecs)) (len-subsum (cdddr vecs)))))

(define (s32vector-empty? vec) (zero? (s32vector-length vec)))

(define (s32vector= vec1 vec2 . vecs)
  (and (s32dyadic-vecs=
        vec1
        0
        (s32vector-length vec1)
        vec2
        0
        (s32vector-length vec2))
       (or (null? vecs)
           (null? (car vecs))
           (s32vector= vec2 (car vecs) (cdr vecs)))))

(define (s32dyadic-vecs= vec1 start1 end1 vec2 start2 end2)
  (cond
   ((not (= end1 end2)) #f)
   ((not (< start1 end1)) #t)
   ((let ((elt1 (s32vector-ref vec1 start1)) (elt2 (s32vector-ref vec2 start2)))
      (= elt1 elt2))
    (s32dyadic-vecs= vec1 (+ start1 1) end1 vec2 (+ start2 1) end2))
   (else #f)))

(define (s32vector-take vec n)
  (let ((v (make-s32vector n))) (s32vector-copy! v 0 vec 0 n) v))

(define (s32vector-take-right vec n)
  (let ((v (make-s32vector n)) (len (s32vector-length vec)))
    (s32vector-copy! v 0 vec (- len n) len)
    v))

(define (s32vector-drop vec n)
  (let* ((len (s32vector-length vec))
         (vlen (- len n))
         (v (make-s32vector vlen)))
    (s32vector-copy! v 0 vec n len)
    v))

(define (s32vector-drop-right vec n)
  (let* ((len (s32vector-length vec))
         (rlen (- len n))
         (v (make-s32vector rlen)))
    (s32vector-copy! v 0 vec 0 rlen)
    v))

(define (s32vector-segment vec n)
  (let loop ((r '()) (i 0) (remain (s32vector-length vec)))
    (if (<= remain 0)
      (reverse r)
      (let ((size (min n remain)))
        (loop
         (cons (s32vector-copy vec i (+ i size)) r)
         (+ i size)
         (- remain size))))))

(define (%s32vectors-ref vecs i) (map (lambda (v) (s32vector-ref v i)) vecs))

(define (s32vector-fold kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((r knil) (i 0))
        (if (= i len) r (loop (kons r (s32vector-ref vec i)) (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((r knil) (i 0))
        (if (= i len)
          r
          (loop (apply kons r (%s32vectors-ref vecs i)) (+ i 1)))))))

(define (s32vector-fold-right kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((r knil) (i (- (s32vector-length vec) 1)))
        (if (negative? i) r (loop (kons r (s32vector-ref vec i)) (- i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((r knil) (i (- len 1)))
        (if (negative? i)
          r
          (loop (apply kons r (%s32vectors-ref vecs i)) (- i 1)))))))

(define (s32vector-map f vec . vecs)
  (if (null? vecs)
    (let* ((len (s32vector-length vec)) (v (make-s32vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (s32vector-set! v i (f (s32vector-ref vec i)))
          (loop (+ i 1))))
      v)
    (let* ((vecs (cons vec vecs))
           (len (apply min (map s32vector-length vecs)))
           (v (make-s32vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (s32vector-set! v i (apply f (%s32vectors-ref vecs i)))
          (loop (+ i 1))))
      v)))

(define (s32vector-map! f vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((i 0))
        (unless (= i len)
          (s32vector-set! vec i (f (s32vector-ref vec i)))
          (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len)
          (s32vector-set! vec i (apply f (%s32vectors-ref vecs i)))
          (loop (+ i 1)))))))

(define (s32vector-for-each f vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((i 0))
        (unless (= i len) (f (s32vector-ref vec i)) (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len) (apply f (%s32vectors-ref vecs i)) (loop (+ i 1)))))))

(define (s32vector-count pred vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((i 0) (r 0))
        (cond
         ((= i (s32vector-length vec)) r)
         ((pred (s32vector-ref vec i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((i 0) (r 0))
        (cond
         ((= i len) r)
         ((apply pred (%s32vectors-ref vecs i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))))

(define (s32vector-cumulate f knil vec)
  (let* ((len (s32vector-length vec)) (v (make-s32vector len)))
    (let loop ((r knil) (i 0))
      (unless (= i len)
        (let ((next (f r (s32vector-ref vec i))))
          (s32vector-set! v i next)
          (loop next (+ i 1)))))
    v))

(define (s32vector-take-while pred vec)
  (let* ((len (s32vector-length vec))
         (idx (s32vector-skip pred vec))
         (idx* (if idx idx len)))
    (s32vector-copy vec 0 idx*)))

(define (s32vector-take-while-right pred vec)
  (let* ((len (s32vector-length vec))
         (idx (s32vector-skip-right pred vec))
         (idx* (if idx (+ idx 1) 0)))
    (s32vector-copy vec idx* len)))

(define (s32vector-drop-while pred vec)
  (let* ((len (s32vector-length vec))
         (idx (s32vector-skip pred vec))
         (idx* (if idx idx len)))
    (s32vector-copy vec idx* len)))

(define (s32vector-drop-while-right pred vec)
  (let* ((len (s32vector-length vec))
         (idx (s32vector-skip-right pred vec))
         (idx* (if idx idx -1)))
    (s32vector-copy vec 0 (+ 1 idx*))))

(define (s32vector-index pred vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (s32vector-ref vec i)) i)
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%s32vectors-ref vecs i)) i)
         (else (loop (+ i 1))))))))

(define (s32vector-index-right pred vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((pred (s32vector-ref vec i)) i)
         (else (loop (- i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((apply pred (%s32vectors-ref vecs i)) i)
         (else (loop (- i 1))))))))

(define (s32vector-skip pred vec . vecs)
  (if (null? vecs)
    (s32vector-index (lambda (x) (not (pred x))) vec)
    (apply s32vector-index (lambda xs (not (apply pred xs))) vec vecs)))

(define (s32vector-skip-right pred vec . vecs)
  (if (null? vecs)
    (s32vector-index-right (lambda (x) (not (pred x))) vec)
    (apply s32vector-index-right (lambda xs (not (apply pred xs))) vec vecs)))

(define (s32vector-any pred vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (s32vector-ref vec i)))
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%s32vectors-ref vecs i)))
         (else (loop (+ i 1))))))))

(define (s32vector-every pred vec . vecs)
  (if (null? vecs)
    (let ((len (s32vector-length vec)))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((pred (s32vector-ref vec i)) => (lambda (r) (loop (+ i 1) r)))
         (else #f))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s32vector-length vecs))))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((apply pred (%s32vectors-ref vecs i))
          =>
          (lambda (r) (loop (+ i 1) r)))
         (else #f))))))

(define (s32vector-partition pred vec)
  (let* ((len (s32vector-length vec))
         (cnt (s32vector-count pred vec))
         (r (make-s32vector len)))
    (let loop ((i 0) (yes 0) (no cnt))
      (cond
       ((= i len) r)
       ((pred (s32vector-ref vec i))
        (s32vector-set! r yes (s32vector-ref vec i))
        (loop (+ i 1) (+ yes 1) no))
       (else
        (s32vector-set! r no (s32vector-ref vec i))
        (loop (+ i 1) yes (+ no 1)))))))

(define (s32vector-filter pred vec)
  (let* ((len (s32vector-length vec))
         (cnt (s32vector-count pred vec))
         (r (make-s32vector cnt)))
    (let loop ((i 0) (j 0))
      (cond
       ((= i len) r)
       ((pred (s32vector-ref vec i))
        (s32vector-set! r j (s32vector-ref vec i))
        (loop (+ i 1) (+ j 1)))
       (else (loop (+ i 1) j))))))

(define (s32vector-remove pred vec)
  (s32vector-filter (lambda (x) (not (pred x))) vec))

(define (s32vector-swap! vec i j)
  (let ((ival (s32vector-ref vec i)) (jval (s32vector-ref vec j)))
    (s32vector-set! vec i jval)
    (s32vector-set! vec j ival)))

(define (s32vector-fill! vec fill (start 0) (end (s32vector-length vec)))
  (unless (= start end)
    (s32vector-set! vec start fill)
    (s32vector-fill! vec fill (+ start 1) end)))

(define (s32vector-reverse! vec (start 0) (end (s32vector-length vec)))
  (let loop ((i start) (j (- end 1)))
    (when (< i j) (s32vector-swap! vec i j) (loop (+ i 1) (- j 1)))))

(define (s32vector-unfold! f vec start end seed)
  (let loop ((i start) (seed seed))
    (when (< i end)
      (let-values (((elt seed) (f i seed)))
        (s32vector-set! vec i elt)
        (loop (+ i 1) seed)))))

(define (s32vector-unfold-right! f vec start end seed)
  (let loop ((i (- end 1)) (seed seed))
    (when (>= i start)
      (let-values (((elt seed) (f i seed)))
        (s32vector-set! vec i elt)
        (loop (- i 1) seed)))))

(define (reverse-s32vector->list vec (start 0) (end (s32vector-length vec)))
  (let loop ((i start) (r '()))
    (if (= i end) r (loop (+ 1 i) (cons (s32vector-ref vec i) r)))))

(define (reverse-list->s32vector list)
  (let* ((len (length list)) (r (make-s32vector len)))
    (let loop ((i 0) (list list))
      (cond
       ((= i len) r)
       (else
        (s32vector-set! r (- len i 1) (car list))
        (loop (+ i 1) (cdr list)))))))

(define (s32vector->vector vec (start 0) (end (s32vector-length vec)))
  (let* ((len (- end start)) (r (make-vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (vector-set! r o (s32vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (vector->s32vector vec (start 0) (end (vector-length vec)))
  (let* ((len (- end start)) (r (make-s32vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (s32vector-set! r o (vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (make-s32vector-generator vec (start 0) (end (s32vector-length vec)))
  (lambda ()
    (if (>= start end)
      eof
      (let ((next (s32vector-ref vec start))) (set! start (+ start 1)) next))))

(define (write-s32vector vec (port (current-output-port)))
  (begin
    (fprintf port "#~A(" 's32)
    (let ((last (- (s32vector-length vec) 1)))
      (let loop ((i 0))
        (cond
         ((= i last) (write (s32vector-ref vec i) port) (display ")" port))
         (else
          (write (s32vector-ref vec i) port)
          (display " " port)
          (loop (+ i 1))))))))

(define (s32vector< vec1 vec2)
  (let ((len1 (s32vector-length vec1)) (len2 (s32vector-length vec2)))
    (cond
     ((< len1 len2) #t)
     ((> len1 len2) #f)
     (else
      (let loop ((i 0))
        (cond
         ((= i len1) #f)
         ((< (s32vector-ref vec1 i) (s32vector-ref vec2 i)) #t)
         ((> (s32vector-ref vec1 i) (s32vector-ref vec2 i)) #f)
         (else (loop (+ i 1)))))))))

(define (s32vector-hash vec)
  (let ((len (min 256 (s32vector-length vec))))
    (let loop ((i 0) (r 0))
      (if (= i len)
        (abs (floor (real-part (inexact->exact r))))
        (loop (+ i 1) (+ r (s32vector-ref vec i)))))))

(define s32vector-comparator
  (make-comparator s32vector? s32vector= s32vector< s32vector-hash))

(module+
 test
 (require rackunit "../128.rkt")
 (define-syntax test
   (syntax-rules ()
     ((_ name expect expr) (test-equal? name expr expect))
     ((_ expect expr) (check-equal? expr expect))))
 (define-syntax test-assert
   (syntax-rules ()
     ((_ name expr) (test-not-false name expr))
     ((_ expr) (check-not-false expr))))
 (define-syntax-rule (test-group name tests ...) (begin tests ...))
 (define (times2 x) (* x 2))
 (define s5 (s32vector 1 2 3 4 5))
 (define s4 (s32vector 1 2 3 4))
 (define s5+ (s32vector 1 2 3 4 6))
 (define (steady i x) (values x x))
 (define (count-up i x) (values x (+ x 1)))
 (define (count-down i x) (values x (- x 1)))
 (define (odd+1 x) (if (odd? x) (+ 1 x) #f))
 (define s32vector< (comparator-ordering-predicate s32vector-comparator))
 (define s32vector-hash (comparator-hash-function s32vector-comparator))
 (define g (make-s32vector-generator s5))
 (define-syntax test-equiv
   (syntax-rules ()
     ((test-equiv expect expr) (test expect (s32vector->list expr)))
     ((test-equiv name expect expr) (test name expect (s32vector->list expr)))))
 (test-group
  "@vector"
  (test-group
   "@vector/constructors"
   (test-equiv "make" '(3 3 3 3 3) (make-s32vector 5 3))
   (test-equiv "@vector" '(-2 -1 0 1 2) (s32vector -2 -1 0 1 2))
   (test-equiv "unfold up" '(10 11 12 13 14) (s32vector-unfold count-up 5 10))
   (test-equiv "unfold down" '(10 9 8 7 6) (s32vector-unfold count-down 5 10))
   (test-equiv "unfold steady" '(10 10 10 10 10) (s32vector-unfold steady 5 10))
   (test-equiv
    "unfold-right up"
    '(14 13 12 11 10)
    (s32vector-unfold-right count-up 5 10))
   (test-equiv
    "unfold-right down"
    '(6 7 8 9 10)
    (s32vector-unfold-right count-down 5 10))
   (test-equiv
    "unfold-right steady"
    '(10 10 10 10 10)
    (s32vector-unfold-right steady 5 10))
   (test-equiv "copy" '(1 2 3 4 5) (s32vector-copy s5))
   (test-assert "copy2" (not (eqv? s5 (s32vector-copy s5))))
   (test-equiv "copy3" '(2 3) (s32vector-copy s5 1 3))
   (test-equiv "reverse-copy" '(5 4 3 2 1) (s32vector-reverse-copy s5))
   (test-equiv "append" '(1 2 3 4 5 1 2 3 4 5) (s32vector-append s5 s5))
   (test-equiv
    "concatenate"
    '(1 2 3 4 5 1 2 3 4 5)
    (s32vector-concatenate (list s5 s5)))
   (test-equiv
    "append-subvectors"
    '(2 3 2 3)
    (s32vector-append-subvectors s5 1 3 s5 1 3)))
  (test-group
   "@vector/predicates"
   (test-assert "@?" (s32? 5))
   (test-assert "@vector?" (s32vector? s5))
   (test-assert "not @vector?" (not (s32vector? #t)))
   (test-assert "empty" (s32vector-empty? (s32vector)))
   (test-assert "not empty" (not (s32vector-empty? s5)))
   (test-assert "=" (s32vector= (s32vector 1 2 3) (s32vector 1 2 3)))
   (test-assert
    "= multi"
    (s32vector= (s32vector 1 2 3) (s32vector 1 2 3) (s32vector 1 2 3)))
   (test-assert "not =" (not (s32vector= (s32vector 1 2 3) (s32vector 3 2 1))))
   (test-assert "not =2" (not (s32vector= (s32vector 1 2 3) (s32vector 1 2))))
   (test-assert
    "not = multi"
    (not (s32vector= (s32vector 1 2 3) (s32vector 1 2 3) (s32vector 3 2 1)))))
  (test-group
   "@vector/selectors"
   (test "ref" 1 (s32vector-ref (s32vector 1 2 3) 0))
   (test "length" 3 (s32vector-length (s32vector 1 2 3))))
  (test-group
   "@vector/iteration"
   (test-equiv "take" '(1 2) (s32vector-take s5 2))
   (test-equiv "take-right" '(4 5) (s32vector-take-right s5 2))
   (test-equiv "drop" '(3 4 5) (s32vector-drop s5 2))
   (test-equiv "drop-right" '(1 2 3) (s32vector-drop-right s5 2))
   (test
    "segment"
    (list (s32vector->list (s32vector 1 2 3)) (s32vector->list (s32vector 4 5)))
    (map s32vector->list (s32vector-segment s5 3)))
   (test "fold" -6 (s32vector-fold - 0 (s32vector 1 2 3)))
   (test
    "fold"
    '(((0 1 4) 2 5) 3 6)
    (s32vector-fold list 0 (s32vector 1 2 3) (s32vector 4 5 6)))
   (test "fold-right" -6 (s32vector-fold-right - 0 (s32vector 1 2 3)))
   (test
    "fold-right"
    '(((0 3 6) 2 5) 1 4)
    (s32vector-fold-right list 0 (s32vector 1 2 3) (s32vector 4 5 6)))
   (test-equiv "map" '(-1 -2 -3 -4 -5) (s32vector-map - s5))
   (test-equiv "map" '(-2 -4 -6 -8 -10) (s32vector-map - s5 s5 s5 s5))
   (let ((v (s32vector 1 2 3 4 5)))
     (s32vector-map! - v)
     (test-equiv "map!" '(-1 -2 -3 -4 -5) v))
   (let ((v (s32vector 1 2 3 4 5)) (v2 (s32vector 6 7 8 9 10)))
     (s32vector-map! + v v2)
     (test-equiv "map!" '(7 9 11 13 15) v))
   (let ((list '()))
     (s32vector-for-each (lambda (e) (set! list (cons e list))) s5)
     (test "for-each" '(5 4 3 2 1) (cons (car list) (cdr list))))
   (let ((list '()))
     (s32vector-for-each
      (lambda (e1 e2) (set! list (cons (cons e1 e2) list)))
      s5
      (s32vector 6 7 8 9 10))
     (test
      "for-each"
      '((5 . 10) (4 . 9) (3 . 8) (2 . 7) (1 . 6))
      (cons (car list) (cdr list))))
   (test "count" 3 (s32vector-count odd? s5))
   (test "count" 2 (s32vector-count > s5 (s32vector 9 2 1 5 3)))
   (test-equiv "cumulate" '(1 3 6 10 15) (s32vector-cumulate + 0 s5)))
  (test-group
   "@vector/searching"
   (test-equiv "take-while" '(1) (s32vector-take-while odd? s5))
   (test-equiv "take-while-right" '(5) (s32vector-take-while-right odd? s5))
   (test-equiv "drop-while" '(2 3 4 5) (s32vector-drop-while odd? s5))
   (test-equiv
    "drop-while-right"
    '(1 2 3 4)
    (s32vector-drop-while-right odd? s5))
   (test-equiv "degenerate take-while" '() (s32vector-take-while inexact? s5))
   (test-equiv
    "degenerate take-while-right"
    '()
    (s32vector-take-while-right inexact? s5))
   (test-equiv
    "degenerate drop-while"
    '(1 2 3 4 5)
    (s32vector-drop-while inexact? s5))
   (test-equiv
    "degenerate drop-while-right"
    '(1 2 3 4 5)
    (s32vector-drop-while-right inexact? s5))
   (test "index" 1 (s32vector-index even? s5))
   (test "index" 2 (s32vector-index < s5 (s32vector 0 0 10 10 0)))
   (test "index-right" 3 (s32vector-index-right even? s5))
   (test "index-right" 3 (s32vector-index-right < s5 (s32vector 0 0 10 10 0)))
   (test "skip" 1 (s32vector-skip odd? s5))
   (test "skip" 2 (s32vector-skip > s5 (s32vector 0 0 10 10 0)))
   (test "skip-right" 3 (s32vector-skip-right odd? s5))
   (test "skip-right" 3 (s32vector-skip-right > s5 (s32vector 0 0 10 10 0)))
   (test "any" 4 (s32vector-any (lambda (x) (and (even? x) (* x 2))) s5))
   (test-assert "not any" (not (s32vector-any inexact? s5)))
   (test "any + 1" 2 (s32vector-any odd+1 s5))
   (test-assert "every" (s32vector-every exact? s5))
   (test-assert "not every" (not (s32vector-every odd? s5)))
   (test-assert "every + 1" (not (s32vector-every odd+1 s5)))
   (test
    "multi-any"
    10
    (s32vector-any
     (lambda (x y) (and (even? x) (even? y) (+ x y)))
     s5
     (s32vector 0 1 2 6 4)))
   (test
    "multi-any 2"
    #f
    (s32vector-any
     (lambda (x y) (and (even? x) (even? y) (+ x y)))
     s5
     (s32vector 0 1 2 5 4)))
   (test
    "multi-every"
    10
    (s32vector-every (lambda (x) (and (exact? x) (* x 2))) s5))
   (test
    "multi-every-2"
    10
    (s32vector-every (lambda (x y) (and (exact? x) (exact? y) (+ x y))) s5 s5))
   (test-assert
    "multi-not every"
    (not (s32vector-every < s5 (s32vector 10 10 10 10 0))))
   (test-equiv "partition" '(1 3 5 2 4) (s32vector-partition odd? s5))
   (test-equiv "filter" '(1 3 5) (s32vector-filter odd? s5))
   (test-equiv "remove" '(2 4) (s32vector-remove odd? s5)))
  (test-group
   "@vector/mutators"
   (let ((v (s32vector 1 2 3)))
     (s32vector-set! v 0 10)
     (test-equiv "set!" '(10 2 3) v))
   (let ((v (s32vector 1 2 3)))
     (s32vector-swap! v 0 1)
     (test-equiv "swap!" '(2 1 3) v))
   (let ((v (s32vector 1 2 3)))
     (s32vector-fill! v 2)
     (test-equiv "fill!" '(2 2 2) v))
   (let ((v (s32vector 1 2 3)))
     (s32vector-fill! v 10 0 2)
     (test-equiv "fill2!" '(10 10 3) v))
   (let ((v (s32vector 1 2 3)))
     (s32vector-reverse! v)
     (test-equiv "reverse!" '(3 2 1) v))
   (let ((v (s32vector 1 2 3)))
     (s32vector-reverse! v 1 3)
     (test-equiv "reverse2!" '(1 3 2) v))
   (let ((v (s32vector 10 20 30 40 50)))
     (s32vector-copy! v 1 s5 2 4)
     (test-equiv "copy!" '(10 3 4 40 50) v))
   (let ((v (s32vector 10 20 30 40 50)))
     (s32vector-reverse-copy! v 1 s5 2 4)
     (test-equiv "reverse-copy!" '(10 4 3 40 50) v))
   (let ((v (s32vector 1 2 3 4 5 6 7 8)))
     (s32vector-unfold! (lambda (_ x) (values (* x 2) (* x 2))) v 1 6 -1)
     (test-equiv "vector-unfold!" '(1 -2 -4 -8 -16 -32 7 8) v))
   (let ((v (s32vector 1 2 3 4 5 6 7 8)))
     (s32vector-unfold-right! (lambda (_ x) (values (* x 2) (* x 2))) v 1 6 -1)
     (test-equiv "vector-unfold!" '(1 -32 -16 -8 -4 -2 7 8) v)))
  (test-group
   "@vector/conversion"
   (test "@vector->list 1" '(1 2 3 4 5) (s32vector->list s5))
   (test "@vector->list 2" '(2 3 4 5) (s32vector->list s5 1))
   (test "@vector->list 3" '(2 3 4) (s32vector->list s5 1 4))
   (test "@vector->vector 1" #(1 2 3 4 5) (s32vector->vector s5))
   (test "@vector->vector 2" #(2 3 4 5) (s32vector->vector s5 1))
   (test "@vector->vector 3" #(2 3 4) (s32vector->vector s5 1 4))
   (test-equiv "list->@vector" '(1 2 3 4 5) (list->s32vector '(1 2 3 4 5)))
   (test-equiv
    "reverse-list->@vector"
    '(5 4 3 2 1)
    (reverse-list->s32vector '(1 2 3 4 5)))
   (test-equiv
    "vector->@vector 1"
    '(1 2 3 4 5)
    (vector->s32vector #(1 2 3 4 5)))
   (test-equiv
    "vector->@vector 2"
    '(2 3 4 5)
    (vector->s32vector #(1 2 3 4 5) 1))
   (test-equiv
    "vector->@vector 3"
    '(2 3 4)
    (vector->s32vector #(1 2 3 4 5) 1 4)))
  (test-group
   "@vector/misc"
   (let ((port (open-output-string)))
     (write-s32vector s5 port)
     (test
      "write-@vector"
      (format "#~S(1 2 3 4 5)" 's32)
      (get-output-string port))
     (close-output-port port))
   (test-assert "@vector< short" (s32vector< s4 s5))
   (test-assert "not @vector< short" (not (s32vector< s5 s4)))
   (test-assert "@vector< samelen" (s32vector< s5 s5+))
   (test-assert "not @vector< samelen" (not (s32vector< s5+ s5+)))
   (test-assert "@vector=" (s32vector= s5+ s5+))
   (test "@vector-hash" 15 (s32vector-hash s5))
   (test "@vector-gen 0" 1 (g))
   (test "@vector-gen 1" 2 (g))
   (test "@vector-gen 2" 3 (g))
   (test "@vector-gen 3" 4 (g))
   (test "@vector-gen 4" 5 (g))
   (test-assert (eof-object? (g))))))

