#lang racket/base
;;; Autogenerated on Tuesday, October 18th, 2022 5:02:47pm
;;; DO NOT EDIT

(require (only-in
          "base.rkt"
          s64?
          s64vector?
          s64vector
          make-s64vector
          s64vector-ref
          s64vector-set!
          s64vector-length
          s64vector->list
          list->s64vector)
         (only-in "../128.rkt" comparator? make-comparator)
         racket/contract)

(provide (all-from-out "base.rkt")
         s64vector-append-subvectors
         (contract-out
          (s64vector-unfold
           (-> procedure? exact-nonnegative-integer? any/c s64vector?))
          (s64vector-unfold-right
           (-> procedure? exact-nonnegative-integer? any/c s64vector?))
          (s64vector-copy
           (->*
            (s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            s64vector?))
          (s64vector-copy!
           (->*
            (s64vector? exact-nonnegative-integer? s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s64vector-reverse-copy
           (->*
            (s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            s64vector?))
          (s64vector-reverse-copy!
           (->*
            (s64vector? exact-nonnegative-integer? s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s64vector-append (-> s64vector? ... s64vector?))
          (s64vector-concatenate (-> (listof s64vector?) s64vector?))
          (s64vector-empty? (-> s64vector? boolean?))
          (s64vector= (-> s64vector? s64vector? s64vector? ... boolean?))
          (s64vector-take (-> s64vector? exact-nonnegative-integer? s64vector?))
          (s64vector-take-right
           (-> s64vector? exact-nonnegative-integer? s64vector?))
          (s64vector-drop (-> s64vector? exact-nonnegative-integer? s64vector?))
          (s64vector-drop-right
           (-> s64vector? exact-nonnegative-integer? s64vector?))
          (s64vector-segment
           (-> s64vector? exact-positive-integer? (listof s64vector?)))
          (s64vector-fold
           (->
            (-> s64? s64? ... any/c any/c)
            any/c
            s64vector?
            s64vector?
            ...
            any/c))
          (s64vector-fold-right
           (->
            (-> s64? s64? ... any/c any/c)
            any/c
            s64vector?
            s64vector?
            ...
            any/c))
          (s64vector-map
           (-> (-> s64? s64? ... s64?) s64vector? s64vector? ... s64vector?))
          (s64vector-map!
           (-> (-> s64? s64? ... s64?) s64vector? s64vector? ... s64vector?))
          (s64vector-for-each
           (-> (-> s64? s64? ... s64?) s64vector? s64vector? ... void?))
          (s64vector-count
           (->
            (-> s64? s64? ... any/c)
            s64vector?
            s64vector?
            ...
            exact-nonnegative-integer?))
          (s64vector-cumulate
           (-> (-> any/c s64? s64?) any/c s64vector? s64vector?))
          (s64vector-take-while (-> (-> s64? any/c) s64vector? s64vector?))
          (s64vector-take-while-right
           (-> (-> s64? any/c) s64vector? s64vector?))
          (s64vector-drop-while (-> (-> s64? any/c) s64vector? s64vector?))
          (s64vector-drop-while-right
           (-> (-> s64? any/c) s64vector? s64vector?))
          (s64vector-index
           (->
            (-> s64? s64? ... any/c)
            s64vector?
            s64vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s64vector-index-right
           (->
            (-> s64? s64? ... any/c)
            s64vector?
            s64vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s64vector-skip
           (->
            (-> s64? s64? ... any/c)
            s64vector?
            s64vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s64vector-skip-right
           (->
            (-> s64? s64? ... any/c)
            s64vector?
            s64vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (s64vector-any
           (-> (-> s64? s64? ... any/c) s64vector? s64vector? ... any))
          (s64vector-every
           (-> (-> s64? s64? ... any/c) s64vector? s64vector? ... any))
          (s64vector-partition
           (->
            (-> s64? any/c)
            s64vector?
            (values s64vector? exact-nonnegative-integer?)))
          (s64vector-filter (-> (-> s64? any/c) s64vector? s64vector?))
          (s64vector-remove (-> (-> s64? any/c) s64vector? s64vector?))
          (s64vector-swap!
           (->
            s64vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            void?))
          (s64vector-fill!
           (->*
            (s64vector? s64?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s64vector-reverse!
           (->*
            (s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (s64vector-unfold!
           (->
            (-> exact-nonnegative-integer? any/c (values s64? any/c))
            s64vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (s64vector-unfold-right!
           (->
            (-> exact-nonnegative-integer? any/c (values s64? any/c))
            s64vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (reverse-s64vector->list
           (->*
            (s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (listof s64?)))
          (reverse-list->s64vector (-> (listof s64?) s64vector?))
          (s64vector->vector
           (->*
            (s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (vectorof s64?)))
          (vector->s64vector
           (->*
            ((vectorof s64?))
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            s64vector?))
          (make-s64vector-generator
           (->*
            (s64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (-> (or/c s64? eof-object?))))
          (write-s64vector (->* (s64vector?) (output-port?) void?))
          (s64vector-comparator comparator?)))

(define (s64vector-unfold f len seed)
  (let ((v (make-s64vector len)))
    (let loop ((i 0) (state seed))
      (unless (= i len)
        (let-values (((value newstate) (f i state)))
          (s64vector-set! v i value)
          (loop (+ i 1) newstate))))
    v))

(define (s64vector-unfold-right f len seed)
  (let ((v (make-s64vector len)))
    (let loop ((i (- len 1)) (state seed))
      (unless (= i -1)
        (let-values (((value newstate) (f i state)))
          (s64vector-set! v i value)
          (loop (- i 1) newstate))))
    v))

(define (s64vector-copy vec (start 0) (end (s64vector-length vec)))
  (let ((v (make-s64vector (- end start))))
    (s64vector-copy! v 0 vec start end)
    v))

(define (s64vector-copy! to at from (start 0) (end (s64vector-length from)))
  (let loop ((at at) (i start))
    (unless (= i end)
      (s64vector-set! to at (s64vector-ref from i))
      (loop (+ at 1) (+ i 1)))))

(define (s64vector-reverse-copy vec (start 0) (end (s64vector-length vec)))
  (let ((v (make-s64vector (- end start))))
    (s64vector-reverse-copy! v 0 vec start end)
    v))

(define (s64vector-reverse-copy!
         to
         at
         from
         (start 0)
         (end (s64vector-length from)))
  (let loop ((at at) (i (- end 1)))
    (unless (< i start)
      (s64vector-set! to at (s64vector-ref from i))
      (loop (+ at 1) (- i 1)))))

(define (s64vector-append . vecs) (s64vector-concatenate vecs))

(define (s64vector-concatenate vecs)
  (let ((v (make-s64vector (len-sum vecs))))
    (let loop ((vecs vecs) (at 0))
      (unless (null? vecs)
        (let ((vec (car vecs)))
          (s64vector-copy! v at vec 0 (s64vector-length vec))
          (loop (cdr vecs) (+ at (s64vector-length vec)))))
      v)))

(define (len-sum vecs)
  (if (null? vecs) 0 (+ (s64vector-length (car vecs)) (len-sum (cdr vecs)))))

(define (s64vector-append-subvectors . args)
  (let ((v (make-s64vector (len-subsum args))))
    (let loop ((args args) (at 0))
      (unless (null? args)
        (let ((vec (car args)) (start (cadr args)) (end (caddr args)))
          (s64vector-copy! v at vec start end)
          (loop (cdddr args) (+ at (- end start))))))
    v))

(define (len-subsum vecs)
  (if (null? vecs)
    0
    (+ (- (caddr vecs) (cadr vecs)) (len-subsum (cdddr vecs)))))

(define (s64vector-empty? vec) (zero? (s64vector-length vec)))

(define (s64vector= vec1 vec2 . vecs)
  (and (s64dyadic-vecs=
        vec1
        0
        (s64vector-length vec1)
        vec2
        0
        (s64vector-length vec2))
       (or (null? vecs)
           (null? (car vecs))
           (s64vector= vec2 (car vecs) (cdr vecs)))))

(define (s64dyadic-vecs= vec1 start1 end1 vec2 start2 end2)
  (cond
   ((not (= end1 end2)) #f)
   ((not (< start1 end1)) #t)
   ((let ((elt1 (s64vector-ref vec1 start1)) (elt2 (s64vector-ref vec2 start2)))
      (= elt1 elt2))
    (s64dyadic-vecs= vec1 (+ start1 1) end1 vec2 (+ start2 1) end2))
   (else #f)))

(define (s64vector-take vec n)
  (let ((v (make-s64vector n))) (s64vector-copy! v 0 vec 0 n) v))

(define (s64vector-take-right vec n)
  (let ((v (make-s64vector n)) (len (s64vector-length vec)))
    (s64vector-copy! v 0 vec (- len n) len)
    v))

(define (s64vector-drop vec n)
  (let* ((len (s64vector-length vec))
         (vlen (- len n))
         (v (make-s64vector vlen)))
    (s64vector-copy! v 0 vec n len)
    v))

(define (s64vector-drop-right vec n)
  (let* ((len (s64vector-length vec))
         (rlen (- len n))
         (v (make-s64vector rlen)))
    (s64vector-copy! v 0 vec 0 rlen)
    v))

(define (s64vector-segment vec n)
  (let loop ((r '()) (i 0) (remain (s64vector-length vec)))
    (if (<= remain 0)
      (reverse r)
      (let ((size (min n remain)))
        (loop
         (cons (s64vector-copy vec i (+ i size)) r)
         (+ i size)
         (- remain size))))))

(define (%s64vectors-ref vecs i) (map (lambda (v) (s64vector-ref v i)) vecs))

(define (s64vector-fold kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((r knil) (i 0))
        (if (= i len) r (loop (kons r (s64vector-ref vec i)) (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((r knil) (i 0))
        (if (= i len)
          r
          (loop (apply kons r (%s64vectors-ref vecs i)) (+ i 1)))))))

(define (s64vector-fold-right kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((r knil) (i (- (s64vector-length vec) 1)))
        (if (negative? i) r (loop (kons r (s64vector-ref vec i)) (- i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((r knil) (i (- len 1)))
        (if (negative? i)
          r
          (loop (apply kons r (%s64vectors-ref vecs i)) (- i 1)))))))

(define (s64vector-map f vec . vecs)
  (if (null? vecs)
    (let* ((len (s64vector-length vec)) (v (make-s64vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (s64vector-set! v i (f (s64vector-ref vec i)))
          (loop (+ i 1))))
      v)
    (let* ((vecs (cons vec vecs))
           (len (apply min (map s64vector-length vecs)))
           (v (make-s64vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (s64vector-set! v i (apply f (%s64vectors-ref vecs i)))
          (loop (+ i 1))))
      v)))

(define (s64vector-map! f vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((i 0))
        (unless (= i len)
          (s64vector-set! vec i (f (s64vector-ref vec i)))
          (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len)
          (s64vector-set! vec i (apply f (%s64vectors-ref vecs i)))
          (loop (+ i 1)))))))

(define (s64vector-for-each f vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((i 0))
        (unless (= i len) (f (s64vector-ref vec i)) (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len) (apply f (%s64vectors-ref vecs i)) (loop (+ i 1)))))))

(define (s64vector-count pred vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((i 0) (r 0))
        (cond
         ((= i (s64vector-length vec)) r)
         ((pred (s64vector-ref vec i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((i 0) (r 0))
        (cond
         ((= i len) r)
         ((apply pred (%s64vectors-ref vecs i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))))

(define (s64vector-cumulate f knil vec)
  (let* ((len (s64vector-length vec)) (v (make-s64vector len)))
    (let loop ((r knil) (i 0))
      (unless (= i len)
        (let ((next (f r (s64vector-ref vec i))))
          (s64vector-set! v i next)
          (loop next (+ i 1)))))
    v))

(define (s64vector-take-while pred vec)
  (let* ((len (s64vector-length vec))
         (idx (s64vector-skip pred vec))
         (idx* (if idx idx len)))
    (s64vector-copy vec 0 idx*)))

(define (s64vector-take-while-right pred vec)
  (let* ((len (s64vector-length vec))
         (idx (s64vector-skip-right pred vec))
         (idx* (if idx (+ idx 1) 0)))
    (s64vector-copy vec idx* len)))

(define (s64vector-drop-while pred vec)
  (let* ((len (s64vector-length vec))
         (idx (s64vector-skip pred vec))
         (idx* (if idx idx len)))
    (s64vector-copy vec idx* len)))

(define (s64vector-drop-while-right pred vec)
  (let* ((len (s64vector-length vec))
         (idx (s64vector-skip-right pred vec))
         (idx* (if idx idx -1)))
    (s64vector-copy vec 0 (+ 1 idx*))))

(define (s64vector-index pred vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (s64vector-ref vec i)) i)
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%s64vectors-ref vecs i)) i)
         (else (loop (+ i 1))))))))

(define (s64vector-index-right pred vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((pred (s64vector-ref vec i)) i)
         (else (loop (- i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((apply pred (%s64vectors-ref vecs i)) i)
         (else (loop (- i 1))))))))

(define (s64vector-skip pred vec . vecs)
  (if (null? vecs)
    (s64vector-index (lambda (x) (not (pred x))) vec)
    (apply s64vector-index (lambda xs (not (apply pred xs))) vec vecs)))

(define (s64vector-skip-right pred vec . vecs)
  (if (null? vecs)
    (s64vector-index-right (lambda (x) (not (pred x))) vec)
    (apply s64vector-index-right (lambda xs (not (apply pred xs))) vec vecs)))

(define (s64vector-any pred vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (s64vector-ref vec i)))
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%s64vectors-ref vecs i)))
         (else (loop (+ i 1))))))))

(define (s64vector-every pred vec . vecs)
  (if (null? vecs)
    (let ((len (s64vector-length vec)))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((pred (s64vector-ref vec i)) => (lambda (r) (loop (+ i 1) r)))
         (else #f))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map s64vector-length vecs))))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((apply pred (%s64vectors-ref vecs i))
          =>
          (lambda (r) (loop (+ i 1) r)))
         (else #f))))))

(define (s64vector-partition pred vec)
  (let* ((len (s64vector-length vec))
         (cnt (s64vector-count pred vec))
         (r (make-s64vector len)))
    (let loop ((i 0) (yes 0) (no cnt))
      (cond
       ((= i len) r)
       ((pred (s64vector-ref vec i))
        (s64vector-set! r yes (s64vector-ref vec i))
        (loop (+ i 1) (+ yes 1) no))
       (else
        (s64vector-set! r no (s64vector-ref vec i))
        (loop (+ i 1) yes (+ no 1)))))))

(define (s64vector-filter pred vec)
  (let* ((len (s64vector-length vec))
         (cnt (s64vector-count pred vec))
         (r (make-s64vector cnt)))
    (let loop ((i 0) (j 0))
      (cond
       ((= i len) r)
       ((pred (s64vector-ref vec i))
        (s64vector-set! r j (s64vector-ref vec i))
        (loop (+ i 1) (+ j 1)))
       (else (loop (+ i 1) j))))))

(define (s64vector-remove pred vec)
  (s64vector-filter (lambda (x) (not (pred x))) vec))

(define (s64vector-swap! vec i j)
  (let ((ival (s64vector-ref vec i)) (jval (s64vector-ref vec j)))
    (s64vector-set! vec i jval)
    (s64vector-set! vec j ival)))

(define (s64vector-fill! vec fill (start 0) (end (s64vector-length vec)))
  (unless (= start end)
    (s64vector-set! vec start fill)
    (s64vector-fill! vec fill (+ start 1) end)))

(define (s64vector-reverse! vec (start 0) (end (s64vector-length vec)))
  (let loop ((i start) (j (- end 1)))
    (when (< i j) (s64vector-swap! vec i j) (loop (+ i 1) (- j 1)))))

(define (s64vector-unfold! f vec start end seed)
  (let loop ((i start) (seed seed))
    (when (< i end)
      (let-values (((elt seed) (f i seed)))
        (s64vector-set! vec i elt)
        (loop (+ i 1) seed)))))

(define (s64vector-unfold-right! f vec start end seed)
  (let loop ((i (- end 1)) (seed seed))
    (when (>= i start)
      (let-values (((elt seed) (f i seed)))
        (s64vector-set! vec i elt)
        (loop (- i 1) seed)))))

(define (reverse-s64vector->list vec (start 0) (end (s64vector-length vec)))
  (let loop ((i start) (r '()))
    (if (= i end) r (loop (+ 1 i) (cons (s64vector-ref vec i) r)))))

(define (reverse-list->s64vector list)
  (let* ((len (length list)) (r (make-s64vector len)))
    (let loop ((i 0) (list list))
      (cond
       ((= i len) r)
       (else
        (s64vector-set! r (- len i 1) (car list))
        (loop (+ i 1) (cdr list)))))))

(define (s64vector->vector vec (start 0) (end (s64vector-length vec)))
  (let* ((len (- end start)) (r (make-vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (vector-set! r o (s64vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (vector->s64vector vec (start 0) (end (vector-length vec)))
  (let* ((len (- end start)) (r (make-s64vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (s64vector-set! r o (vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (make-s64vector-generator vec (start 0) (end (s64vector-length vec)))
  (lambda ()
    (if (>= start end)
      eof
      (let ((next (s64vector-ref vec start))) (set! start (+ start 1)) next))))

(define (write-s64vector vec (port (current-output-port)))
  (fprintf port "#~A(" 's64)
  (let ((last (- (s64vector-length vec) 1)))
    (let loop ((i 0))
      (cond
       ((= i last) (write (s64vector-ref vec i) port) (display ")" port))
       (else
        (write (s64vector-ref vec i) port)
        (display " " port)
        (loop (+ i 1)))))))

(define (s64vector< vec1 vec2)
  (let ((len1 (s64vector-length vec1)) (len2 (s64vector-length vec2)))
    (cond
     ((< len1 len2) #t)
     ((> len1 len2) #f)
     (else
      (let loop ((i 0))
        (cond
         ((= i len1) #f)
         ((< (s64vector-ref vec1 i) (s64vector-ref vec2 i)) #t)
         ((> (s64vector-ref vec1 i) (s64vector-ref vec2 i)) #f)
         (else (loop (+ i 1)))))))))

(define (s64vector-hash vec)
  (let ((len (min 256 (s64vector-length vec))))
    (let loop ((i 0) (r 0))
      (if (= i len)
        (abs (floor (real-part (inexact->exact r))))
        (loop (+ i 1) (+ r (s64vector-ref vec i)))))))

(define s64vector-comparator
  (make-comparator s64vector? s64vector= s64vector< s64vector-hash))

(module+
 test
 (require rackunit "../128.rkt")
 (define-syntax test
   (syntax-rules ()
     ((_ name expect expr) (test-equal? name expr expect))
     ((_ expect expr) (check-equal? expr expect))))
 (define-syntax test-assert
   (syntax-rules ()
     ((_ name expr) (test-not-false name expr))
     ((_ expr) (check-not-false expr))))
 (define-syntax-rule (test-group name tests ...) (begin tests ...))
 (define (times2 x) (* x 2))
 (define s5 (s64vector 1 2 3 4 5))
 (define s4 (s64vector 1 2 3 4))
 (define s5+ (s64vector 1 2 3 4 6))
 (define (steady i x) (values x x))
 (define (count-up i x) (values x (+ x 1)))
 (define (count-down i x) (values x (- x 1)))
 (define (odd+1 x) (if (odd? x) (+ 1 x) #f))
 (define s64vector< (comparator-ordering-predicate s64vector-comparator))
 (define s64vector-hash (comparator-hash-function s64vector-comparator))
 (define g (make-s64vector-generator s5))
 (define-syntax test-equiv
   (syntax-rules ()
     ((test-equiv expect expr) (test expect (s64vector->list expr)))
     ((test-equiv name expect expr) (test name expect (s64vector->list expr)))))
 (test-group
  "@vector"
  (test-group
   "@vector/constructors"
   (test-equiv "make" '(3 3 3 3 3) (make-s64vector 5 3))
   (test-equiv "@vector" '(-2 -1 0 1 2) (s64vector -2 -1 0 1 2))
   (test-equiv "unfold up" '(10 11 12 13 14) (s64vector-unfold count-up 5 10))
   (test-equiv "unfold down" '(10 9 8 7 6) (s64vector-unfold count-down 5 10))
   (test-equiv "unfold steady" '(10 10 10 10 10) (s64vector-unfold steady 5 10))
   (test-equiv
    "unfold-right up"
    '(14 13 12 11 10)
    (s64vector-unfold-right count-up 5 10))
   (test-equiv
    "unfold-right down"
    '(6 7 8 9 10)
    (s64vector-unfold-right count-down 5 10))
   (test-equiv
    "unfold-right steady"
    '(10 10 10 10 10)
    (s64vector-unfold-right steady 5 10))
   (test-equiv "copy" '(1 2 3 4 5) (s64vector-copy s5))
   (test-assert "copy2" (not (eqv? s5 (s64vector-copy s5))))
   (test-equiv "copy3" '(2 3) (s64vector-copy s5 1 3))
   (test-equiv "reverse-copy" '(5 4 3 2 1) (s64vector-reverse-copy s5))
   (test-equiv "append" '(1 2 3 4 5 1 2 3 4 5) (s64vector-append s5 s5))
   (test-equiv
    "concatenate"
    '(1 2 3 4 5 1 2 3 4 5)
    (s64vector-concatenate (list s5 s5)))
   (test-equiv
    "append-subvectors"
    '(2 3 2 3)
    (s64vector-append-subvectors s5 1 3 s5 1 3)))
  (test-group
   "@vector/predicates"
   (test-assert "@?" (s64? 5))
   (test-assert "@vector?" (s64vector? s5))
   (test-assert "not @vector?" (not (s64vector? #t)))
   (test-assert "empty" (s64vector-empty? (s64vector)))
   (test-assert "not empty" (not (s64vector-empty? s5)))
   (test-assert "=" (s64vector= (s64vector 1 2 3) (s64vector 1 2 3)))
   (test-assert
    "= multi"
    (s64vector= (s64vector 1 2 3) (s64vector 1 2 3) (s64vector 1 2 3)))
   (test-assert "not =" (not (s64vector= (s64vector 1 2 3) (s64vector 3 2 1))))
   (test-assert "not =2" (not (s64vector= (s64vector 1 2 3) (s64vector 1 2))))
   (test-assert
    "not = multi"
    (not (s64vector= (s64vector 1 2 3) (s64vector 1 2 3) (s64vector 3 2 1)))))
  (test-group
   "@vector/selectors"
   (test "ref" 1 (s64vector-ref (s64vector 1 2 3) 0))
   (test "length" 3 (s64vector-length (s64vector 1 2 3))))
  (test-group
   "@vector/iteration"
   (test-equiv "take" '(1 2) (s64vector-take s5 2))
   (test-equiv "take-right" '(4 5) (s64vector-take-right s5 2))
   (test-equiv "drop" '(3 4 5) (s64vector-drop s5 2))
   (test-equiv "drop-right" '(1 2 3) (s64vector-drop-right s5 2))
   (test
    "segment"
    (list (s64vector->list (s64vector 1 2 3)) (s64vector->list (s64vector 4 5)))
    (map s64vector->list (s64vector-segment s5 3)))
   (test "fold" -6 (s64vector-fold - 0 (s64vector 1 2 3)))
   (test
    "fold"
    '(((0 1 4) 2 5) 3 6)
    (s64vector-fold list 0 (s64vector 1 2 3) (s64vector 4 5 6)))
   (test "fold-right" -6 (s64vector-fold-right - 0 (s64vector 1 2 3)))
   (test
    "fold-right"
    '(((0 3 6) 2 5) 1 4)
    (s64vector-fold-right list 0 (s64vector 1 2 3) (s64vector 4 5 6)))
   (test-equiv "map" '(-1 -2 -3 -4 -5) (s64vector-map - s5))
   (test-equiv "map" '(-2 -4 -6 -8 -10) (s64vector-map - s5 s5 s5 s5))
   (let ((v (s64vector 1 2 3 4 5)))
     (s64vector-map! - v)
     (test-equiv "map!" '(-1 -2 -3 -4 -5) v))
   (let ((v (s64vector 1 2 3 4 5)) (v2 (s64vector 6 7 8 9 10)))
     (s64vector-map! + v v2)
     (test-equiv "map!" '(7 9 11 13 15) v))
   (let ((list '()))
     (s64vector-for-each (lambda (e) (set! list (cons e list))) s5)
     (test "for-each" '(5 4 3 2 1) (cons (car list) (cdr list))))
   (let ((list '()))
     (s64vector-for-each
      (lambda (e1 e2) (set! list (cons (cons e1 e2) list)))
      s5
      (s64vector 6 7 8 9 10))
     (test
      "for-each"
      '((5 . 10) (4 . 9) (3 . 8) (2 . 7) (1 . 6))
      (cons (car list) (cdr list))))
   (test "count" 3 (s64vector-count odd? s5))
   (test "count" 2 (s64vector-count > s5 (s64vector 9 2 1 5 3)))
   (test-equiv "cumulate" '(1 3 6 10 15) (s64vector-cumulate + 0 s5)))
  (test-group
   "@vector/searching"
   (test-equiv "take-while" '(1) (s64vector-take-while odd? s5))
   (test-equiv "take-while-right" '(5) (s64vector-take-while-right odd? s5))
   (test-equiv "drop-while" '(2 3 4 5) (s64vector-drop-while odd? s5))
   (test-equiv
    "drop-while-right"
    '(1 2 3 4)
    (s64vector-drop-while-right odd? s5))
   (test-equiv "degenerate take-while" '() (s64vector-take-while inexact? s5))
   (test-equiv
    "degenerate take-while-right"
    '()
    (s64vector-take-while-right inexact? s5))
   (test-equiv
    "degenerate drop-while"
    '(1 2 3 4 5)
    (s64vector-drop-while inexact? s5))
   (test-equiv
    "degenerate drop-while-right"
    '(1 2 3 4 5)
    (s64vector-drop-while-right inexact? s5))
   (test "index" 1 (s64vector-index even? s5))
   (test "index" 2 (s64vector-index < s5 (s64vector 0 0 10 10 0)))
   (test "index-right" 3 (s64vector-index-right even? s5))
   (test "index-right" 3 (s64vector-index-right < s5 (s64vector 0 0 10 10 0)))
   (test "skip" 1 (s64vector-skip odd? s5))
   (test "skip" 2 (s64vector-skip > s5 (s64vector 0 0 10 10 0)))
   (test "skip-right" 3 (s64vector-skip-right odd? s5))
   (test "skip-right" 3 (s64vector-skip-right > s5 (s64vector 0 0 10 10 0)))
   (test "any" 4 (s64vector-any (lambda (x) (and (even? x) (* x 2))) s5))
   (test-assert "not any" (not (s64vector-any inexact? s5)))
   (test "any + 1" 2 (s64vector-any odd+1 s5))
   (test-assert "every" (s64vector-every exact? s5))
   (test-assert "not every" (not (s64vector-every odd? s5)))
   (test-assert "every + 1" (not (s64vector-every odd+1 s5)))
   (test
    "multi-any"
    10
    (s64vector-any
     (lambda (x y) (and (even? x) (even? y) (+ x y)))
     s5
     (s64vector 0 1 2 6 4)))
   (test
    "multi-any 2"
    #f
    (s64vector-any
     (lambda (x y) (and (even? x) (even? y) (+ x y)))
     s5
     (s64vector 0 1 2 5 4)))
   (test
    "multi-every"
    10
    (s64vector-every (lambda (x) (and (exact? x) (* x 2))) s5))
   (test
    "multi-every-2"
    10
    (s64vector-every (lambda (x y) (and (exact? x) (exact? y) (+ x y))) s5 s5))
   (test-assert
    "multi-not every"
    (not (s64vector-every < s5 (s64vector 10 10 10 10 0))))
   (test-equiv "partition" '(1 3 5 2 4) (s64vector-partition odd? s5))
   (test-equiv "filter" '(1 3 5) (s64vector-filter odd? s5))
   (test-equiv "remove" '(2 4) (s64vector-remove odd? s5)))
  (test-group
   "@vector/mutators"
   (let ((v (s64vector 1 2 3)))
     (s64vector-set! v 0 10)
     (test-equiv "set!" '(10 2 3) v))
   (let ((v (s64vector 1 2 3)))
     (s64vector-swap! v 0 1)
     (test-equiv "swap!" '(2 1 3) v))
   (let ((v (s64vector 1 2 3)))
     (s64vector-fill! v 2)
     (test-equiv "fill!" '(2 2 2) v))
   (let ((v (s64vector 1 2 3)))
     (s64vector-fill! v 10 0 2)
     (test-equiv "fill2!" '(10 10 3) v))
   (let ((v (s64vector 1 2 3)))
     (s64vector-reverse! v)
     (test-equiv "reverse!" '(3 2 1) v))
   (let ((v (s64vector 1 2 3)))
     (s64vector-reverse! v 1 3)
     (test-equiv "reverse2!" '(1 3 2) v))
   (let ((v (s64vector 10 20 30 40 50)))
     (s64vector-copy! v 1 s5 2 4)
     (test-equiv "copy!" '(10 3 4 40 50) v))
   (let ((v (s64vector 10 20 30 40 50)))
     (s64vector-reverse-copy! v 1 s5 2 4)
     (test-equiv "reverse-copy!" '(10 4 3 40 50) v))
   (let ((v (s64vector 1 2 3 4 5 6 7 8)))
     (s64vector-unfold! (lambda (_ x) (values (* x 2) (* x 2))) v 1 6 -1)
     (test-equiv "vector-unfold!" '(1 -2 -4 -8 -16 -32 7 8) v))
   (let ((v (s64vector 1 2 3 4 5 6 7 8)))
     (s64vector-unfold-right! (lambda (_ x) (values (* x 2) (* x 2))) v 1 6 -1)
     (test-equiv "vector-unfold!" '(1 -32 -16 -8 -4 -2 7 8) v)))
  (test-group
   "@vector/conversion"
   (test "@vector->list 1" '(1 2 3 4 5) (s64vector->list s5))
   (test "@vector->list 2" '(2 3 4 5) (s64vector->list s5 1))
   (test "@vector->list 3" '(2 3 4) (s64vector->list s5 1 4))
   (test "@vector->vector 1" #(1 2 3 4 5) (s64vector->vector s5))
   (test "@vector->vector 2" #(2 3 4 5) (s64vector->vector s5 1))
   (test "@vector->vector 3" #(2 3 4) (s64vector->vector s5 1 4))
   (test-equiv "list->@vector" '(1 2 3 4 5) (list->s64vector '(1 2 3 4 5)))
   (test-equiv
    "reverse-list->@vector"
    '(5 4 3 2 1)
    (reverse-list->s64vector '(1 2 3 4 5)))
   (test-equiv
    "vector->@vector 1"
    '(1 2 3 4 5)
    (vector->s64vector #(1 2 3 4 5)))
   (test-equiv
    "vector->@vector 2"
    '(2 3 4 5)
    (vector->s64vector #(1 2 3 4 5) 1))
   (test-equiv
    "vector->@vector 3"
    '(2 3 4)
    (vector->s64vector #(1 2 3 4 5) 1 4)))
  (test-group
   "@vector/misc"
   (let ((port (open-output-string)))
     (write-s64vector s5 port)
     (test
      "write-@vector"
      (format "#~S(1 2 3 4 5)" 's64)
      (get-output-string port))
     (close-output-port port))
   (test-assert "@vector< short" (s64vector< s4 s5))
   (test-assert "not @vector< short" (not (s64vector< s5 s4)))
   (test-assert "@vector< samelen" (s64vector< s5 s5+))
   (test-assert "not @vector< samelen" (not (s64vector< s5+ s5+)))
   (test-assert "@vector=" (s64vector= s5+ s5+))
   (test "@vector-hash" 15 (s64vector-hash s5))
   (test "@vector-gen 0" 1 (g))
   (test "@vector-gen 1" 2 (g))
   (test "@vector-gen 2" 3 (g))
   (test "@vector-gen 3" 4 (g))
   (test "@vector-gen 4" 5 (g))
   (test-assert (eof-object? (g))))))

