#lang racket/base
;;; Autogenerated on 2023-10-07T16:04:06
;;; DO NOT EDIT

(require (only-in
          "base.rkt"
          u64?
          u64vector?
          u64vector
          make-u64vector
          u64vector-ref
          u64vector-set!
          u64vector-length
          u64vector->list
          list->u64vector)
         (only-in "../128.rkt" comparator? make-comparator)
         racket/contract
         racket/unsafe/ops)

(provide (all-from-out "base.rkt")
         u64vector-append-subvectors
         (contract-out
          (u64vector-unfold
           (-> procedure? exact-nonnegative-integer? any/c u64vector?))
          (u64vector-unfold-right
           (-> procedure? exact-nonnegative-integer? any/c u64vector?))
          (u64vector-copy
           (->*
            (u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            u64vector?))
          (u64vector-copy!
           (->*
            (u64vector? exact-nonnegative-integer? u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u64vector-reverse-copy
           (->*
            (u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            u64vector?))
          (u64vector-reverse-copy!
           (->*
            (u64vector? exact-nonnegative-integer? u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u64vector-append (-> u64vector? ... u64vector?))
          (u64vector-concatenate (-> (listof u64vector?) u64vector?))
          (u64vector-empty? (-> u64vector? boolean?))
          (u64vector= (-> u64vector? u64vector? u64vector? ... boolean?))
          (u64vector-take (-> u64vector? exact-nonnegative-integer? u64vector?))
          (u64vector-take-right
           (-> u64vector? exact-nonnegative-integer? u64vector?))
          (u64vector-drop (-> u64vector? exact-nonnegative-integer? u64vector?))
          (u64vector-drop-right
           (-> u64vector? exact-nonnegative-integer? u64vector?))
          (u64vector-segment
           (-> u64vector? exact-positive-integer? (listof u64vector?)))
          (u64vector-fold
           (->i
            ((kons
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 2)))))
             (knil any/c)
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ any/c)))
          (u64vector-fold-right
           (->i
            ((kons
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 2)))))
             (knil any/c)
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ any/c)))
          (u64vector-map
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> u64?)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ u64vector?)))
          (u64vector-map!
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> u64?)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ u64vector?)))
          (u64vector-for-each
           (->i
            ((proc
              (vecs)
              (lambda (f)
                (and (procedure? f)
                     (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ void?)))
          (u64vector-count
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ exact-nonnegative-integer?)))
          (u64vector-cumulate
           (-> (-> any/c u64? u64?) any/c u64vector? u64vector?))
          (u64vector-take-while (-> (-> u64? any/c) u64vector? u64vector?))
          (u64vector-take-while-right
           (-> (-> u64? any/c) u64vector? u64vector?))
          (u64vector-drop-while (-> (-> u64? any/c) u64vector? u64vector?))
          (u64vector-drop-while-right
           (-> (-> u64? any/c) u64vector? u64vector?))
          (u64vector-index
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (u64vector-index-right
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (u64vector-skip
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (u64vector-skip-right
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ (or/c exact-nonnegative-integer? #f))))
          (u64vector-any
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ any/c)))
          (u64vector-every
           (->i
            ((proc
              (vecs)
              (and/c
               (unconstrained-domain-> any/c)
               (lambda (f) (procedure-arity-includes? f (+ (length vecs) 1)))))
             (vec1 u64vector?))
            ()
            #:rest
            (vecs (listof u64vector?))
            (_ any/c)))
          (u64vector-partition
           (->
            (-> u64? any/c)
            u64vector?
            (values u64vector? exact-nonnegative-integer?)))
          (u64vector-filter (-> (-> u64? any/c) u64vector? u64vector?))
          (u64vector-remove (-> (-> u64? any/c) u64vector? u64vector?))
          (u64vector-swap!
           (->
            u64vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            void?))
          (u64vector-fill!
           (->*
            (u64vector? u64?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u64vector-reverse!
           (->*
            (u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u64vector-unfold!
           (->
            (-> exact-nonnegative-integer? any/c (values u64? any/c))
            u64vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (u64vector-unfold-right!
           (->
            (-> exact-nonnegative-integer? any/c (values u64? any/c))
            u64vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (reverse-u64vector->list
           (->*
            (u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (listof u64?)))
          (reverse-list->u64vector (-> (listof u64?) u64vector?))
          (u64vector->vector
           (->*
            (u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (vectorof u64?)))
          (vector->u64vector
           (->*
            ((vectorof u64?))
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            u64vector?))
          (make-u64vector-generator
           (->*
            (u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (-> (or/c u64? eof-object?))))
          (write-u64vector (->* (u64vector?) (output-port?) void?))
          (u64vector-comparator comparator?)
          (in-u64vector
           (->*
            (u64vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            sequence?))))

(module+
 unsafe
 (require (only-in
           (submod "base.rkt" unsafe)
           u64?
           u64vector?
           u64vector
           make-u64vector
           u64vector-ref
           u64vector-set!
           u64vector-length
           u64vector->list
           list->u64vector))
 (provide (all-from-out (submod "base.rkt" unsafe))
          u64vector-unfold
          u64vector-unfold-right
          u64vector-copy
          u64vector-copy!
          u64vector-reverse-copy
          u64vector-reverse-copy!
          u64vector-append
          u64vector-concatenate
          u64vector-empty?
          u64vector=
          u64vector-take
          u64vector-take-right
          u64vector-drop
          u64vector-drop-right
          u64vector-segment
          u64vector-fold
          u64vector-fold-right
          u64vector-map
          u64vector-map!
          u64vector-for-each
          u64vector-count
          u64vector-cumulate
          u64vector-take-while
          u64vector-take-while-right
          u64vector-drop-while
          u64vector-drop-while-right
          u64vector-index
          u64vector-index-right
          u64vector-skip
          u64vector-skip-right
          u64vector-any
          u64vector-every
          u64vector-partition
          u64vector-filter
          u64vector-remove
          u64vector-swap!
          u64vector-fill!
          u64vector-reverse!
          u64vector-unfold!
          u64vector-unfold-right!
          reverse-u64vector->list
          u64vector->vector
          make-u64vector-generator
          write-u64vector
          u64vector-comparator
          u64vector-append-subvectors
          in-u64vector))

(define (u64vector-unfold f len seed)
  (let ((v (make-u64vector len)))
    (let loop ((i 0) (state seed))
      (unless (= i len)
        (let-values (((value newstate) (f i state)))
          (u64vector-set! v i value)
          (loop (+ i 1) newstate))))
    v))

(define (u64vector-unfold-right f len seed)
  (let ((v (make-u64vector len)))
    (let loop ((i (- len 1)) (state seed))
      (unless (= i -1)
        (let-values (((value newstate) (f i state)))
          (u64vector-set! v i value)
          (loop (- i 1) newstate))))
    v))

(define (u64vector-copy vec (start 0) (end (u64vector-length vec)))
  (let ((v (make-u64vector (- end start))))
    (u64vector-copy! v 0 vec start end)
    v))

(define (u64vector-copy! to at from (start 0) (end (u64vector-length from)))
  (let loop ((at at) (i start))
    (unless (= i end)
      (u64vector-set! to at (u64vector-ref from i))
      (loop (+ at 1) (+ i 1)))))

(define (u64vector-reverse-copy vec (start 0) (end (u64vector-length vec)))
  (let ((v (make-u64vector (- end start))))
    (u64vector-reverse-copy! v 0 vec start end)
    v))

(define (u64vector-reverse-copy!
         to
         at
         from
         (start 0)
         (end (u64vector-length from)))
  (let loop ((at at) (i (- end 1)))
    (unless (< i start)
      (u64vector-set! to at (u64vector-ref from i))
      (loop (+ at 1) (- i 1)))))

(define (u64vector-append . vecs) (u64vector-concatenate vecs))

(define (u64vector-concatenate vecs)
  (let ((v (make-u64vector (len-sum vecs))))
    (let loop ((vecs vecs) (at 0))
      (unless (null? vecs)
        (let ((vec (car vecs)))
          (u64vector-copy! v at vec 0 (u64vector-length vec))
          (loop (cdr vecs) (+ at (u64vector-length vec)))))
      v)))

(define (len-sum vecs)
  (if (null? vecs) 0 (+ (u64vector-length (car vecs)) (len-sum (cdr vecs)))))

(define (u64vector-append-subvectors . args)
  (let ((v (make-u64vector (len-subsum args))))
    (let loop ((args args) (at 0))
      (unless (null? args)
        (let ((vec (car args)) (start (cadr args)) (end (caddr args)))
          (u64vector-copy! v at vec start end)
          (loop (cdddr args) (+ at (- end start))))))
    v))

(define (len-subsum vecs)
  (if (null? vecs)
    0
    (+ (- (caddr vecs) (cadr vecs)) (len-subsum (cdddr vecs)))))

(define (u64vector-empty? vec) (zero? (u64vector-length vec)))

(define (u64vector= vec1 vec2 . vecs)
  (and (u64dyadic-vecs=
        vec1
        0
        (u64vector-length vec1)
        vec2
        0
        (u64vector-length vec2))
       (or (null? vecs)
           (null? (car vecs))
           (u64vector= vec2 (car vecs) (cdr vecs)))))

(define (u64dyadic-vecs= vec1 start1 end1 vec2 start2 end2)
  (cond
   ((not (= end1 end2)) #f)
   ((not (< start1 end1)) #t)
   ((let ((elt1 (u64vector-ref vec1 start1)) (elt2 (u64vector-ref vec2 start2)))
      (= elt1 elt2))
    (u64dyadic-vecs= vec1 (+ start1 1) end1 vec2 (+ start2 1) end2))
   (else #f)))

(define (u64vector-take vec n)
  (let ((v (make-u64vector n))) (u64vector-copy! v 0 vec 0 n) v))

(define (u64vector-take-right vec n)
  (let ((v (make-u64vector n)) (len (u64vector-length vec)))
    (u64vector-copy! v 0 vec (- len n) len)
    v))

(define (u64vector-drop vec n)
  (let* ((len (u64vector-length vec))
         (vlen (- len n))
         (v (make-u64vector vlen)))
    (u64vector-copy! v 0 vec n len)
    v))

(define (u64vector-drop-right vec n)
  (let* ((len (u64vector-length vec))
         (rlen (- len n))
         (v (make-u64vector rlen)))
    (u64vector-copy! v 0 vec 0 rlen)
    v))

(define (u64vector-segment vec n)
  (let loop ((r '()) (i 0) (remain (u64vector-length vec)))
    (if (<= remain 0)
      (reverse r)
      (let ((size (min n remain)))
        (loop
         (cons (u64vector-copy vec i (+ i size)) r)
         (+ i size)
         (- remain size))))))

(define (%u64vectors-ref vecs i) (map (lambda (v) (u64vector-ref v i)) vecs))

(define (u64vector-fold kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((r knil) (i 0))
        (if (= i len) r (loop (kons r (u64vector-ref vec i)) (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((r knil) (i 0))
        (if (= i len)
          r
          (loop (apply kons r (%u64vectors-ref vecs i)) (+ i 1)))))))

(define (u64vector-fold-right kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((r knil) (i (- (u64vector-length vec) 1)))
        (if (negative? i) r (loop (kons r (u64vector-ref vec i)) (- i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((r knil) (i (- len 1)))
        (if (negative? i)
          r
          (loop (apply kons r (%u64vectors-ref vecs i)) (- i 1)))))))

(define (u64vector-map f vec . vecs)
  (if (null? vecs)
    (let* ((len (u64vector-length vec)) (v (make-u64vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (u64vector-set! v i (f (u64vector-ref vec i)))
          (loop (+ i 1))))
      v)
    (let* ((vecs (cons vec vecs))
           (len (apply min (map u64vector-length vecs)))
           (v (make-u64vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (u64vector-set! v i (apply f (%u64vectors-ref vecs i)))
          (loop (+ i 1))))
      v)))

(define (u64vector-map! f vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((i 0))
        (unless (= i len)
          (u64vector-set! vec i (f (u64vector-ref vec i)))
          (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len)
          (u64vector-set! vec i (apply f (%u64vectors-ref vecs i)))
          (loop (+ i 1)))))))

(define (u64vector-for-each f vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((i 0))
        (unless (= i len) (f (u64vector-ref vec i)) (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((i 0))
        (unless (= i len) (apply f (%u64vectors-ref vecs i)) (loop (+ i 1)))))))

(define (u64vector-count pred vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((i 0) (r 0))
        (cond
         ((= i (u64vector-length vec)) r)
         ((pred (u64vector-ref vec i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((i 0) (r 0))
        (cond
         ((= i len) r)
         ((apply pred (%u64vectors-ref vecs i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))))

(define (u64vector-cumulate f knil vec)
  (let* ((len (u64vector-length vec)) (v (make-u64vector len)))
    (let loop ((r knil) (i 0))
      (unless (= i len)
        (let ((next (f r (u64vector-ref vec i))))
          (u64vector-set! v i next)
          (loop next (+ i 1)))))
    v))

(define (u64vector-take-while pred vec)
  (let* ((len (u64vector-length vec))
         (idx (u64vector-skip pred vec))
         (idx* (if idx idx len)))
    (u64vector-copy vec 0 idx*)))

(define (u64vector-take-while-right pred vec)
  (let* ((len (u64vector-length vec))
         (idx (u64vector-skip-right pred vec))
         (idx* (if idx (+ idx 1) 0)))
    (u64vector-copy vec idx* len)))

(define (u64vector-drop-while pred vec)
  (let* ((len (u64vector-length vec))
         (idx (u64vector-skip pred vec))
         (idx* (if idx idx len)))
    (u64vector-copy vec idx* len)))

(define (u64vector-drop-while-right pred vec)
  (let* ((len (u64vector-length vec))
         (idx (u64vector-skip-right pred vec))
         (idx* (if idx idx -1)))
    (u64vector-copy vec 0 (+ 1 idx*))))

(define (u64vector-index pred vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (u64vector-ref vec i)) i)
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%u64vectors-ref vecs i)) i)
         (else (loop (+ i 1))))))))

(define (u64vector-index-right pred vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((pred (u64vector-ref vec i)) i)
         (else (loop (- i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((apply pred (%u64vectors-ref vecs i)) i)
         (else (loop (- i 1))))))))

(define (u64vector-skip pred vec . vecs)
  (if (null? vecs)
    (u64vector-index (lambda (x) (not (pred x))) vec)
    (apply u64vector-index (lambda xs (not (apply pred xs))) vec vecs)))

(define (u64vector-skip-right pred vec . vecs)
  (if (null? vecs)
    (u64vector-index-right (lambda (x) (not (pred x))) vec)
    (apply u64vector-index-right (lambda xs (not (apply pred xs))) vec vecs)))

(define (u64vector-any pred vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (u64vector-ref vec i)))
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%u64vectors-ref vecs i)))
         (else (loop (+ i 1))))))))

(define (u64vector-every pred vec . vecs)
  (if (null? vecs)
    (let ((len (u64vector-length vec)))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((pred (u64vector-ref vec i)) => (lambda (r) (loop (+ i 1) r)))
         (else #f))))
    (let* ((vecs (cons vec vecs)) (len (apply min (map u64vector-length vecs))))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((apply pred (%u64vectors-ref vecs i))
          =>
          (lambda (r) (loop (+ i 1) r)))
         (else #f))))))

(define (u64vector-partition pred vec)
  (let* ((len (u64vector-length vec))
         (cnt (u64vector-count pred vec))
         (r (make-u64vector len)))
    (let loop ((i 0) (yes 0) (no cnt))
      (cond
       ((= i len) (values r cnt))
       ((pred (u64vector-ref vec i))
        (u64vector-set! r yes (u64vector-ref vec i))
        (loop (+ i 1) (+ yes 1) no))
       (else
        (u64vector-set! r no (u64vector-ref vec i))
        (loop (+ i 1) yes (+ no 1)))))))

(define (u64vector-filter pred vec)
  (let* ((len (u64vector-length vec))
         (cnt (u64vector-count pred vec))
         (r (make-u64vector cnt)))
    (let loop ((i 0) (j 0))
      (cond
       ((= i len) r)
       ((pred (u64vector-ref vec i))
        (u64vector-set! r j (u64vector-ref vec i))
        (loop (+ i 1) (+ j 1)))
       (else (loop (+ i 1) j))))))

(define (u64vector-remove pred vec)
  (u64vector-filter (lambda (x) (not (pred x))) vec))

(define (u64vector-swap! vec i j)
  (let ((ival (u64vector-ref vec i)) (jval (u64vector-ref vec j)))
    (u64vector-set! vec i jval)
    (u64vector-set! vec j ival)))

(define (u64vector-fill! vec fill (start 0) (end (u64vector-length vec)))
  (unless (= start end)
    (u64vector-set! vec start fill)
    (u64vector-fill! vec fill (+ start 1) end)))

(define (u64vector-reverse! vec (start 0) (end (u64vector-length vec)))
  (let loop ((i start) (j (- end 1)))
    (when (< i j) (u64vector-swap! vec i j) (loop (+ i 1) (- j 1)))))

(define (u64vector-unfold! f vec start end seed)
  (let loop ((i start) (seed seed))
    (when (< i end)
      (let-values (((elt seed) (f i seed)))
        (u64vector-set! vec i elt)
        (loop (+ i 1) seed)))))

(define (u64vector-unfold-right! f vec start end seed)
  (let loop ((i (- end 1)) (seed seed))
    (when (>= i start)
      (let-values (((elt seed) (f i seed)))
        (u64vector-set! vec i elt)
        (loop (- i 1) seed)))))

(define (reverse-u64vector->list vec (start 0) (end (u64vector-length vec)))
  (let loop ((i start) (r '()))
    (if (= i end) r (loop (+ 1 i) (cons (u64vector-ref vec i) r)))))

(define (reverse-list->u64vector list)
  (let* ((len (length list)) (r (make-u64vector len)))
    (let loop ((i 0) (list list))
      (cond
       ((= i len) r)
       (else
        (u64vector-set! r (- len i 1) (car list))
        (loop (+ i 1) (cdr list)))))))

(define (u64vector->vector vec (start 0) (end (u64vector-length vec)))
  (let* ((len (- end start)) (r (make-vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (vector-set! r o (u64vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (vector->u64vector vec (start 0) (end (vector-length vec)))
  (let* ((len (- end start)) (r (make-u64vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (u64vector-set! r o (vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (make-u64vector-generator vec (start 0) (end (u64vector-length vec)))
  (lambda ()
    (if (>= start end)
      eof
      (let ((next (u64vector-ref vec start))) (set! start (+ start 1)) next))))

(define (write-u64vector vec (port (current-output-port)))
  (begin
    (fprintf port "#~A(" 'u64)
    (let ((last (- (u64vector-length vec) 1)))
      (let loop ((i 0))
        (cond
         ((= i last) (write (u64vector-ref vec i) port) (display ")" port))
         (else
          (write (u64vector-ref vec i) port)
          (display " " port)
          (loop (+ i 1))))))))

(define (u64vector< vec1 vec2)
  (let ((len1 (u64vector-length vec1)) (len2 (u64vector-length vec2)))
    (cond
     ((< len1 len2) #t)
     ((> len1 len2) #f)
     (else
      (let loop ((i 0))
        (cond
         ((= i len1) #f)
         ((< (u64vector-ref vec1 i) (u64vector-ref vec2 i)) #t)
         ((> (u64vector-ref vec1 i) (u64vector-ref vec2 i)) #f)
         (else (loop (+ i 1)))))))))

(define (u64vector-hash vec)
  (let ((len (min 256 (u64vector-length vec))))
    (let loop ((i 0) (r 0))
      (if (= i len)
        (abs (floor (real-part (inexact->exact r))))
        (loop (+ i 1) (+ r (u64vector-ref vec i)))))))

(define u64vector-comparator
  (make-comparator u64vector? u64vector= u64vector< u64vector-hash))

(define (in-u64vector vec (start 0) (end (u64vector-length vec)))
  (make-do-sequence
   (lambda ()
     (values
      (lambda (i) (u64vector-ref vec i))
      #f
      add1
      start
      (lambda (i) (< i end))
      #f
      #f))))

