#lang racket/base
;;; Autogenerated on 2022-10-25T17:34:11
;;; DO NOT EDIT

(require (only-in
          "base.rkt"
          u8?
          u8vector?
          u8vector
          make-u8vector
          u8vector-ref
          u8vector-set!
          u8vector-length
          u8vector->list
          list->u8vector)
         (only-in "../128.rkt" comparator? make-comparator)
         racket/contract
         racket/unsafe/ops)

(provide (all-from-out "base.rkt")
         u8vector-append-subvectors
         (contract-out
          (u8vector-unfold
           (-> procedure? exact-nonnegative-integer? any/c u8vector?))
          (u8vector-unfold-right
           (-> procedure? exact-nonnegative-integer? any/c u8vector?))
          (u8vector-copy
           (->*
            (u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            u8vector?))
          (u8vector-copy!
           (->*
            (u8vector? exact-nonnegative-integer? u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u8vector-reverse-copy
           (->*
            (u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            u8vector?))
          (u8vector-reverse-copy!
           (->*
            (u8vector? exact-nonnegative-integer? u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u8vector-append (-> u8vector? ... u8vector?))
          (u8vector-concatenate (-> (listof u8vector?) u8vector?))
          (u8vector-empty? (-> u8vector? boolean?))
          (u8vector= (-> u8vector? u8vector? u8vector? ... boolean?))
          (u8vector-take (-> u8vector? exact-nonnegative-integer? u8vector?))
          (u8vector-take-right
           (-> u8vector? exact-nonnegative-integer? u8vector?))
          (u8vector-drop (-> u8vector? exact-nonnegative-integer? u8vector?))
          (u8vector-drop-right
           (-> u8vector? exact-nonnegative-integer? u8vector?))
          (u8vector-segment
           (-> u8vector? exact-positive-integer? (listof u8vector?)))
          (u8vector-fold (-> procedure? any/c u8vector? u8vector? ... any/c))
          (u8vector-fold-right
           (-> procedure? any/c u8vector? u8vector? ... any/c))
          (u8vector-map (-> procedure? u8vector? u8vector? ... u8vector?))
          (u8vector-map! (-> procedure? u8vector? u8vector? ... u8vector?))
          (u8vector-for-each (-> procedure? u8vector? u8vector? ... void?))
          (u8vector-count
           (-> procedure? u8vector? u8vector? ... exact-nonnegative-integer?))
          (u8vector-cumulate (-> (-> any/c u8? u8?) any/c u8vector? u8vector?))
          (u8vector-take-while (-> (-> u8? any/c) u8vector? u8vector?))
          (u8vector-take-while-right (-> (-> u8? any/c) u8vector? u8vector?))
          (u8vector-drop-while (-> (-> u8? any/c) u8vector? u8vector?))
          (u8vector-drop-while-right (-> (-> u8? any/c) u8vector? u8vector?))
          (u8vector-index
           (->
            procedure?
            u8vector?
            u8vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (u8vector-index-right
           (->
            procedure?
            u8vector?
            u8vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (u8vector-skip
           (->
            procedure?
            u8vector?
            u8vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (u8vector-skip-right
           (->
            procedure?
            u8vector?
            u8vector?
            ...
            (or/c exact-nonnegative-integer? #f)))
          (u8vector-any (-> procedure? u8vector? u8vector? ... any))
          (u8vector-every (-> procedure? u8vector? u8vector? ... any))
          (u8vector-partition
           (->
            (-> u8? any/c)
            u8vector?
            (values u8vector? exact-nonnegative-integer?)))
          (u8vector-filter (-> (-> u8? any/c) u8vector? u8vector?))
          (u8vector-remove (-> (-> u8? any/c) u8vector? u8vector?))
          (u8vector-swap!
           (->
            u8vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            void?))
          (u8vector-fill!
           (->*
            (u8vector? u8?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u8vector-reverse!
           (->*
            (u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            void?))
          (u8vector-unfold!
           (->
            (-> exact-nonnegative-integer? any/c (values u8? any/c))
            u8vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (u8vector-unfold-right!
           (->
            (-> exact-nonnegative-integer? any/c (values u8? any/c))
            u8vector?
            exact-nonnegative-integer?
            exact-nonnegative-integer?
            any/c
            void?))
          (reverse-u8vector->list
           (->*
            (u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (listof u8?)))
          (reverse-list->u8vector (-> (listof u8?) u8vector?))
          (u8vector->vector
           (->*
            (u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (vectorof u8?)))
          (vector->u8vector
           (->*
            ((vectorof u8?))
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            u8vector?))
          (make-u8vector-generator
           (->*
            (u8vector?)
            (exact-nonnegative-integer? exact-nonnegative-integer?)
            (-> (or/c u8? eof-object?))))
          (write-u8vector (->* (u8vector?) (output-port?) void?))
          (u8vector-comparator comparator?)))

(define (u8vector-unfold f len seed)
  (let ((v (make-u8vector len)))
    (let loop ((i 0) (state seed))
      (unless (= i len)
        (let-values (((value newstate) (f i state)))
          (unsafe-bytes-set! v i value)
          (loop (+ i 1) newstate))))
    v))

(define (u8vector-unfold-right f len seed)
  (let ((v (make-u8vector len)))
    (let loop ((i (- len 1)) (state seed))
      (unless (= i -1)
        (let-values (((value newstate) (f i state)))
          (unsafe-bytes-set! v i value)
          (loop (- i 1) newstate))))
    v))

(define (u8vector-copy vec (start 0) (end (unsafe-bytes-length vec)))
  (let ((v (make-u8vector (- end start))))
    (u8vector-copy! v 0 vec start end)
    v))

(define (u8vector-copy! to at from (start 0) (end (unsafe-bytes-length from)))
  (let loop ((at at) (i start))
    (unless (= i end)
      (u8vector-set! to at (u8vector-ref from i))
      (loop (+ at 1) (+ i 1)))))

(define (u8vector-reverse-copy vec (start 0) (end (unsafe-bytes-length vec)))
  (let ((v (make-u8vector (- end start))))
    (u8vector-reverse-copy! v 0 vec start end)
    v))

(define (u8vector-reverse-copy!
         to
         at
         from
         (start 0)
         (end (unsafe-bytes-length from)))
  (let loop ((at at) (i (- end 1)))
    (unless (< i start)
      (u8vector-set! to at (u8vector-ref from i))
      (loop (+ at 1) (- i 1)))))

(define (u8vector-append . vecs) (u8vector-concatenate vecs))

(define (u8vector-concatenate vecs)
  (let ((v (make-u8vector (len-sum vecs))))
    (let loop ((vecs vecs) (at 0))
      (unless (null? vecs)
        (let ((vec (car vecs)))
          (u8vector-copy! v at vec 0 (unsafe-bytes-length vec))
          (loop (cdr vecs) (+ at (unsafe-bytes-length vec)))))
      v)))

(define (len-sum vecs)
  (if (null? vecs) 0 (+ (unsafe-bytes-length (car vecs)) (len-sum (cdr vecs)))))

(define (u8vector-append-subvectors . args)
  (let ((v (make-u8vector (len-subsum args))))
    (let loop ((args args) (at 0))
      (unless (null? args)
        (let ((vec (car args)) (start (cadr args)) (end (caddr args)))
          (u8vector-copy! v at vec start end)
          (loop (cdddr args) (+ at (- end start))))))
    v))

(define (len-subsum vecs)
  (if (null? vecs)
    0
    (+ (- (caddr vecs) (cadr vecs)) (len-subsum (cdddr vecs)))))

(define (u8vector-empty? vec) (zero? (unsafe-bytes-length vec)))

(define (u8vector= vec1 vec2 . vecs)
  (and (u8dyadic-vecs=
        vec1
        0
        (unsafe-bytes-length vec1)
        vec2
        0
        (unsafe-bytes-length vec2))
       (or (null? vecs)
           (null? (car vecs))
           (u8vector= vec2 (car vecs) (cdr vecs)))))

(define (u8dyadic-vecs= vec1 start1 end1 vec2 start2 end2)
  (cond
   ((not (= end1 end2)) #f)
   ((not (< start1 end1)) #t)
   ((let ((elt1 (u8vector-ref vec1 start1)) (elt2 (u8vector-ref vec2 start2)))
      (= elt1 elt2))
    (u8dyadic-vecs= vec1 (+ start1 1) end1 vec2 (+ start2 1) end2))
   (else #f)))

(define (u8vector-take vec n)
  (let ((v (make-u8vector n))) (u8vector-copy! v 0 vec 0 n) v))

(define (u8vector-take-right vec n)
  (let ((v (make-u8vector n)) (len (unsafe-bytes-length vec)))
    (u8vector-copy! v 0 vec (- len n) len)
    v))

(define (u8vector-drop vec n)
  (let* ((len (unsafe-bytes-length vec))
         (vlen (- len n))
         (v (make-u8vector vlen)))
    (u8vector-copy! v 0 vec n len)
    v))

(define (u8vector-drop-right vec n)
  (let* ((len (unsafe-bytes-length vec))
         (rlen (- len n))
         (v (make-u8vector rlen)))
    (u8vector-copy! v 0 vec 0 rlen)
    v))

(define (u8vector-segment vec n)
  (let loop ((r '()) (i 0) (remain (unsafe-bytes-length vec)))
    (if (<= remain 0)
      (reverse r)
      (let ((size (min n remain)))
        (loop
         (cons (u8vector-copy vec i (+ i size)) r)
         (+ i size)
         (- remain size))))))

(define (%u8vectors-ref vecs i) (map (lambda (v) (u8vector-ref v i)) vecs))

(define (u8vector-fold kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((r knil) (i 0))
        (if (= i len) r (loop (kons r (unsafe-bytes-ref vec i)) (+ i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((r knil) (i 0))
        (if (= i len)
          r
          (loop (apply kons r (%u8vectors-ref vecs i)) (+ i 1)))))))

(define (u8vector-fold-right kons knil vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((r knil) (i (- (unsafe-bytes-length vec) 1)))
        (if (negative? i) r (loop (kons r (unsafe-bytes-ref vec i)) (- i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((r knil) (i (- len 1)))
        (if (negative? i)
          r
          (loop (apply kons r (%u8vectors-ref vecs i)) (- i 1)))))))

(define (u8vector-map f vec . vecs)
  (if (null? vecs)
    (let* ((len (unsafe-bytes-length vec)) (v (make-u8vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (unsafe-bytes-set! v i (f (unsafe-bytes-ref vec i)))
          (loop (+ i 1))))
      v)
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs)))
           (v (make-u8vector len)))
      (let loop ((i 0))
        (unless (= i len)
          (u8vector-set! v i (apply f (%u8vectors-ref vecs i)))
          (loop (+ i 1))))
      v)))

(define (u8vector-map! f vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((i 0))
        (unless (= i len)
          (unsafe-bytes-set! vec i (f (unsafe-bytes-ref vec i)))
          (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((i 0))
        (unless (= i len)
          (u8vector-set! vec i (apply f (%u8vectors-ref vecs i)))
          (loop (+ i 1)))))))

(define (u8vector-for-each f vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((i 0))
        (unless (= i len) (f (unsafe-bytes-ref vec i)) (loop (+ i 1)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((i 0))
        (unless (= i len) (apply f (%u8vectors-ref vecs i)) (loop (+ i 1)))))))

(define (u8vector-count pred vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((i 0) (r 0))
        (cond
         ((= i (unsafe-bytes-length vec)) r)
         ((pred (unsafe-bytes-ref vec i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((i 0) (r 0))
        (cond
         ((= i len) r)
         ((apply pred (%u8vectors-ref vecs i)) (loop (+ i 1) (+ r 1)))
         (else (loop (+ i 1) r)))))))

(define (u8vector-cumulate f knil vec)
  (let* ((len (unsafe-bytes-length vec)) (v (make-u8vector len)))
    (let loop ((r knil) (i 0))
      (unless (= i len)
        (let ((next (f r (unsafe-bytes-ref vec i))))
          (unsafe-bytes-set! v i next)
          (loop next (+ i 1)))))
    v))

(define (u8vector-take-while pred vec)
  (let* ((len (unsafe-bytes-length vec))
         (idx (u8vector-skip pred vec))
         (idx* (if idx idx len)))
    (u8vector-copy vec 0 idx*)))

(define (u8vector-take-while-right pred vec)
  (let* ((len (unsafe-bytes-length vec))
         (idx (u8vector-skip-right pred vec))
         (idx* (if idx (+ idx 1) 0)))
    (u8vector-copy vec idx* len)))

(define (u8vector-drop-while pred vec)
  (let* ((len (unsafe-bytes-length vec))
         (idx (u8vector-skip pred vec))
         (idx* (if idx idx len)))
    (u8vector-copy vec idx* len)))

(define (u8vector-drop-while-right pred vec)
  (let* ((len (unsafe-bytes-length vec))
         (idx (u8vector-skip-right pred vec))
         (idx* (if idx idx -1)))
    (u8vector-copy vec 0 (+ 1 idx*))))

(define (u8vector-index pred vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (unsafe-bytes-ref vec i)) i)
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%u8vectors-ref vecs i)) i)
         (else (loop (+ i 1))))))))

(define (u8vector-index-right pred vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((pred (unsafe-bytes-ref vec i)) i)
         (else (loop (- i 1))))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((i (- len 1)))
        (cond
         ((negative? i) #f)
         ((apply pred (%u8vectors-ref vecs i)) i)
         (else (loop (- i 1))))))))

(define (u8vector-skip pred vec . vecs)
  (if (null? vecs)
    (u8vector-index (lambda (x) (not (pred x))) vec)
    (apply u8vector-index (lambda xs (not (apply pred xs))) vec vecs)))

(define (u8vector-skip-right pred vec . vecs)
  (if (null? vecs)
    (u8vector-index-right (lambda (x) (not (pred x))) vec)
    (apply u8vector-index-right (lambda xs (not (apply pred xs))) vec vecs)))

(define (u8vector-any pred vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((pred (unsafe-bytes-ref vec i)))
         (else (loop (+ i 1))))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((i 0))
        (cond
         ((= i len) #f)
         ((apply pred (%u8vectors-ref vecs i)))
         (else (loop (+ i 1))))))))

(define (u8vector-every pred vec . vecs)
  (if (null? vecs)
    (let ((len (unsafe-bytes-length vec)))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((pred (unsafe-bytes-ref vec i)) => (lambda (r) (loop (+ i 1) r)))
         (else #f))))
    (let* ((vecs (cons vec vecs))
           (len (apply min (map unsafe-bytes-length vecs))))
      (let loop ((i 0) (last #t))
        (cond
         ((= i len) last)
         ((apply pred (%u8vectors-ref vecs i)) => (lambda (r) (loop (+ i 1) r)))
         (else #f))))))

(define (u8vector-partition pred vec)
  (let* ((len (unsafe-bytes-length vec))
         (cnt (u8vector-count pred vec))
         (r (make-u8vector len)))
    (let loop ((i 0) (yes 0) (no cnt))
      (cond
       ((= i len) r)
       ((pred (unsafe-bytes-ref vec i))
        (unsafe-bytes-set! r yes (unsafe-bytes-ref vec i))
        (loop (+ i 1) (+ yes 1) no))
       (else
        (unsafe-bytes-set! r no (unsafe-bytes-ref vec i))
        (loop (+ i 1) yes (+ no 1)))))))

(define (u8vector-filter pred vec)
  (let* ((len (unsafe-bytes-length vec))
         (cnt (u8vector-count pred vec))
         (r (make-u8vector cnt)))
    (let loop ((i 0) (j 0))
      (cond
       ((= i len) r)
       ((pred (unsafe-bytes-ref vec i))
        (unsafe-bytes-set! r j (unsafe-bytes-ref vec i))
        (loop (+ i 1) (+ j 1)))
       (else (loop (+ i 1) j))))))

(define (u8vector-remove pred vec)
  (u8vector-filter (lambda (x) (not (pred x))) vec))

(define (u8vector-swap! vec i j)
  (let ((ival (u8vector-ref vec i)) (jval (u8vector-ref vec j)))
    (u8vector-set! vec i jval)
    (u8vector-set! vec j ival)))

(define (u8vector-fill! vec fill (start 0) (end (unsafe-bytes-length vec)))
  (unless (= start end)
    (u8vector-set! vec start fill)
    (u8vector-fill! vec fill (+ start 1) end)))

(define (u8vector-reverse! vec (start 0) (end (unsafe-bytes-length vec)))
  (let loop ((i start) (j (- end 1)))
    (when (< i j) (u8vector-swap! vec i j) (loop (+ i 1) (- j 1)))))

(define (u8vector-unfold! f vec start end seed)
  (let loop ((i start) (seed seed))
    (when (< i end)
      (let-values (((elt seed) (f i seed)))
        (u8vector-set! vec i elt)
        (loop (+ i 1) seed)))))

(define (u8vector-unfold-right! f vec start end seed)
  (let loop ((i (- end 1)) (seed seed))
    (when (>= i start)
      (let-values (((elt seed) (f i seed)))
        (u8vector-set! vec i elt)
        (loop (- i 1) seed)))))

(define (reverse-u8vector->list vec (start 0) (end (unsafe-bytes-length vec)))
  (let loop ((i start) (r '()))
    (if (= i end) r (loop (+ 1 i) (cons (u8vector-ref vec i) r)))))

(define (reverse-list->u8vector list)
  (let* ((len (length list)) (r (make-u8vector len)))
    (let loop ((i 0) (list list))
      (cond
       ((= i len) r)
       (else
        (u8vector-set! r (- len i 1) (car list))
        (loop (+ i 1) (cdr list)))))))

(define (u8vector->vector vec (start 0) (end (unsafe-bytes-length vec)))
  (let* ((len (- end start)) (r (make-vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (vector-set! r o (u8vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (vector->u8vector vec (start 0) (end (vector-length vec)))
  (let* ((len (- end start)) (r (make-u8vector len)))
    (let loop ((i start) (o 0))
      (cond
       ((= i end) r)
       (else (u8vector-set! r o (vector-ref vec i)) (loop (+ i 1) (+ o 1)))))))

(define (make-u8vector-generator vec (start 0) (end (unsafe-bytes-length vec)))
  (lambda ()
    (if (>= start end)
      eof
      (let ((next (u8vector-ref vec start))) (set! start (+ start 1)) next))))

(define (write-u8vector vec (port (current-output-port)))
  (begin
    (fprintf port "#~A(" 'u8)
    (let ((last (- (unsafe-bytes-length vec) 1)))
      (let loop ((i 0))
        (cond
         ((= i last) (write (unsafe-bytes-ref vec i) port) (display ")" port))
         (else
          (write (unsafe-bytes-ref vec i) port)
          (display " " port)
          (loop (+ i 1))))))))

(define (u8vector< vec1 vec2)
  (let ((len1 (unsafe-bytes-length vec1)) (len2 (unsafe-bytes-length vec2)))
    (cond
     ((< len1 len2) #t)
     ((> len1 len2) #f)
     (else
      (let loop ((i 0))
        (cond
         ((= i len1) #f)
         ((< (unsafe-bytes-ref vec1 i) (unsafe-bytes-ref vec2 i)) #t)
         ((> (unsafe-bytes-ref vec1 i) (unsafe-bytes-ref vec2 i)) #f)
         (else (loop (+ i 1)))))))))

(define (u8vector-hash vec)
  (let ((len (min 256 (unsafe-bytes-length vec))))
    (let loop ((i 0) (r 0))
      (if (= i len)
        (abs (floor (real-part (inexact->exact r))))
        (loop (+ i 1) (+ r (unsafe-bytes-ref vec i)))))))

(define u8vector-comparator
  (make-comparator u8vector? u8vector= u8vector< u8vector-hash))

